"""Generate rust-verifier/src/kg.rs from rules/queries.edn.

REQ-DSL-031: kg.rs runs compiled queries via Cozo and returns row vectors.

Each defquery becomes:
  - a Cozo script (Datalog syntax)
  - a dispatch entry in `ingest_and_summarize` that runs the script
    against the claim graph and pushes any returned row as a defect

The intermediate `rules/queries.edn` is written by booklogic.cljs.tmpl's
emit-queries-edn; this module reads it and emits Rust source.

Cozo is embedded; we use `cozo::DbInstance::new("mem", "", "")` for the
in-memory backend. The graph is populated at verifier startup from the
incoming claims; the queries run as a Phase-2 sweep after the SMT walk.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from scripts._edn_reader import Keyword
from scripts._io import read_edn_file


class CodegenError(ValueError):
    """Raised when a query is malformed for kg codegen."""


SUPPORTED_BACKENDS = {Keyword("cozo")}

HEADER_TOP = """\
// GENERATED BY neurosym-forge codegen_kg — DO NOT EDIT BY HAND.
// Edit rules/booklogic/queries.edn instead, then run:
//   npm run codegen-kg
//
// One Cozo script per defquery; each runs at verification time against
// an in-memory claim graph populated from the incoming claims slice.

use crate::ir::{Claim, Error, GraphSummary};

#[cfg(feature = "kg")]
use cozo::{DataValue, DbInstance, NamedRows};

/// Default Cozo query timeout in milliseconds. Overridden by the
/// `VERIFIER_DATALOG_TIMEOUT_MS` env var. REQ-DATALOG-044.
pub const DEFAULT_DATALOG_TIMEOUT_MS: u64 = 10_000;

fn datalog_timeout_ms() -> u64 {
    std::env::var("VERIFIER_DATALOG_TIMEOUT_MS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(DEFAULT_DATALOG_TIMEOUT_MS)
}

/// Result of running a single defquery against the in-memory Cozo
/// instance. `sample` carries either a short Debug-rendered row
/// (used by the verdict surface) or `"<timeout>"` when the per-query
/// timeout fires.
#[derive(Debug, Clone)]
pub struct QueryRunResult {
    pub name: String,
    pub rows: usize,
    pub sample: Option<String>,
    pub timed_out: bool,
}

/// Parse a list of `(name, datalog-source)` pairs from a defquery EDN
/// payload of the shape
/// `{:queries [{:id "Q001" :source "?[c] := claim[c, _]"} ...]}`.
#[cfg(feature = "kg")]
pub fn parse_query_edn(query_edn: &str) -> Result<Vec<(String, String)>, String> {
    use edn_rs::{Edn, EdnError};
    let parsed: Edn = query_edn
        .parse::<Edn>()
        .map_err(|e: EdnError| format!("parse: {e}"))?;
    let queries = match parsed.get(":queries") {
        Some(Edn::Vector(v)) => v.clone().to_vec(),
        Some(Edn::List(l)) => l.clone().to_vec(),
        Some(_) | None => return Err("missing or non-vector :queries".into()),
    };
    let mut out = Vec::with_capacity(queries.len());
    for q in queries {
        let id = match q.get(":id") {
            Some(Edn::Str(s)) => s.clone(),
            Some(Edn::Key(k)) => k.trim_start_matches(':').to_string(),
            _ => return Err("query missing :id".into()),
        };
        let source = match q.get(":source") {
            Some(Edn::Str(s)) => s.clone(),
            _ => return Err(format!("query {id} missing :source")),
        };
        out.push((id, source));
    }
    Ok(out)
}

#[cfg(feature = "kg")]
fn run_one_script(
    db: &DbInstance,
    name: &str,
    source: &str,
    timeout_ms: u64,
) -> Result<NamedRows, String> {
    use std::sync::mpsc;
    use std::thread;
    use std::time::Duration;

    let (tx, rx) = mpsc::channel::<Result<NamedRows, String>>();
    let source_owned = source.to_string();
    let name_owned = name.to_string();
    let db_clone = db.clone();
    thread::spawn(move || {
        let result = db_clone
            .run_script(
                &source_owned,
                Default::default(),
                cozo::ScriptMutability::Immutable,
            )
            .map_err(|e| format!("cozo run {name_owned}: {e}"));
        let _ = tx.send(result);
    });
    match rx.recv_timeout(Duration::from_millis(timeout_ms)) {
        Ok(r) => r,
        Err(mpsc::RecvTimeoutError::Timeout) => Err("<timeout>".into()),
        Err(e) => Err(format!("cozo channel: {e}")),
    }
}

/// Run a Datalog source as a one-shot constraint check against a fresh
/// in-memory Cozo instance. A non-empty result means the constraint
/// produced a defect row; the row count is returned to the caller.
/// REQ-DATALOG-041.
#[cfg(feature = "kg")]
pub fn evaluate_constraint(name: &str, datalog_source: &str) -> Result<usize, String> {
    let db = DbInstance::new("mem", "", "").map_err(|e| format!("cozo init: {e}"))?;
    let timeout_ms = datalog_timeout_ms();
    let rows = run_one_script(&db, name, datalog_source, timeout_ms)?;
    Ok(rows.rows.len())
}

#[cfg(not(feature = "kg"))]
pub fn evaluate_constraint(_name: &str, _datalog_source: &str) -> Result<usize, String> {
    Err("compiled without `kg` feature".into())
}

/// Run every defquery declared in `query_edn` against an in-memory
/// Cozo instance and collect the resulting `NamedRows`. A query that
/// exceeds `VERIFIER_DATALOG_TIMEOUT_MS` (default 10_000 ms) is
/// recorded as a timeout result and the loop continues without
/// panicking. REQ-DATALOG-040, REQ-DATALOG-044.
#[cfg(feature = "kg")]
pub fn run_queries(query_edn: &str) -> Result<Vec<QueryRunResult>, String> {
    let db = DbInstance::new("mem", "", "").map_err(|e| format!("cozo init: {e}"))?;
    let timeout_ms = datalog_timeout_ms();
    let queries = parse_query_edn(query_edn)?;
    let mut results = Vec::with_capacity(queries.len());
    for (name, source) in queries {
        match run_one_script(&db, &name, &source, timeout_ms) {
            Ok(rows) => {
                let row_count = rows.rows.len();
                let sample = rows.rows.first().map(|r| format!("{r:?}"));
                results.push(QueryRunResult {
                    name,
                    rows: row_count,
                    sample,
                    timed_out: false,
                });
            }
            Err(e) if e == "<timeout>" => {
                results.push(QueryRunResult {
                    name,
                    rows: 0,
                    sample: Some("<timeout>".into()),
                    timed_out: true,
                });
            }
            Err(e) => {
                results.push(QueryRunResult {
                    name,
                    rows: 0,
                    sample: Some(format!("<error: {e}>")),
                    timed_out: false,
                });
            }
        }
    }
    Ok(results)
}

#[cfg(not(feature = "kg"))]
pub fn run_queries(_query_edn: &str) -> Result<Vec<QueryRunResult>, String> {
    Ok(vec![])
}

#[cfg(feature = "kg")]
fn build_db(claims: &[Claim]) -> Result<DbInstance, Error> {
    let db = DbInstance::new("mem", "", "")
        .map_err(|e| Error::Kg(format!("cozo init: {e}")))?;
    // Populate a minimal `claim {id, source}` relation; expand as the
    // schema grows. v0.4 only models the two ir::Claim fields.
    db.run_script(
        ":create claim {id: String => source: String}",
        Default::default(),
        cozo::ScriptMutability::Mutable,
    ).map_err(|e| Error::Kg(format!("cozo create: {e}")))?;
"""

# Emitted between the base `claim` relation and the claim-insert loop. The
# generated defqueries read namespaced relations (e.g. `claim/load-bearing`,
# `claim/posterior`) that are NOT part of the ir::Claim model; if they are
# never `:create`d, Cozo errors on the unknown relation and
# `ingest_and_summarize` returns Err on every call (issue #141). We declare
# each referenced relation here (empty) so the queries evaluate to zero rows
# instead of erroring. They are populated once the claim model carries the
# corresponding per-claim data.
HEADER_RELATION = """\
    // Declare `{rel}` ({why}); referenced by a generated defquery but
    // not yet populated from the claim model. Created empty so the query
    // returns zero rows rather than erroring on an unknown relation.
    db.run_script(
        ":create {rel} {{id: String => {col}: {ty}}}",
        Default::default(),
        cozo::ScriptMutability::Mutable,
    ).map_err(|e| Error::Kg(format!("cozo create {rel}: {{e}}")))?;
"""

HEADER_BOTTOM = """\
    for c in claims {
        let script = format!(
            "?[id, source] <- [['{}', '{}']] :put claim {{id, source}}",
            c.id.replace("'", "\\\\'"),
            c.source.replace("'", "\\\\'"),
        );
        db.run_script(&script, Default::default(), cozo::ScriptMutability::Mutable)
            .map_err(|e| Error::Kg(format!("cozo insert: {e}")))?;
    }
    Ok(db)
}

#[cfg(feature = "kg")]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    let db = build_db(claims)?;
    let mut contradictions: Vec<(String, String)> = Vec::new();
"""

FOOTER = """\
    Ok(GraphSummary {
        claim_count: claims.len(),
        contradictions,
    })
}

#[cfg(not(feature = "kg"))]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    Ok(GraphSummary { claim_count: claims.len(), contradictions: vec![] })
}
"""


def generate_kg_source(queries: list[dict]) -> str:
    """Emit a complete kg.rs file from a list of query dicts."""
    body_lines: list[str] = []
    for q in queries:
        _require(q, "id")
        _require(q, "backend")
        backend = q[Keyword("backend")]
        if backend not in SUPPORTED_BACKENDS:
            raise CodegenError(
                f"query {q.get(Keyword('id'))!r}: unknown backend {backend!r}; "
                f"expected one of {SUPPORTED_BACKENDS}"
            )
        body_lines.append(_emit_query_block(q))
    body = "\n".join(body_lines) if body_lines else "    // no queries declared\n"
    header = HEADER_TOP + _emit_relation_creates(queries) + HEADER_BOTTOM
    return header + body + FOOTER


# Cozo column type for the value column of a referenced relation, inferred
# from how the query constrains it.
_RUST_TYPE = {"bool": "Bool", "int": "Int", "float": "Float", "str": "String"}


def _emit_relation_creates(queries: list[dict]) -> str:
    """Emit a `:create` block for every non-base relation the queries read.

    The base `claim {id => source}` relation is already created by
    HEADER_TOP. Any other relation a defquery reads (e.g.
    `claim/load-bearing`, `claim/posterior`) must also exist, or Cozo
    errors on the unknown relation. We create them empty.
    """
    out = []
    for rel, col, ty in _relations_from_queries(queries):
        why = f"value column typed {ty}"
        out.append(
            HEADER_RELATION.format(rel=rel, col=col, ty=ty, why=why)
        )
    return "".join(out)


def _cozo_relation_name(raw: str) -> str:
    """Sanitise an EDN predicate name to a legal Cozo stored-relation name.

    Cozo relation names are plain identifiers (`[A-Za-z_][A-Za-z0-9_]*`);
    `/` (namespace) and `-` (kebab-case) are illegal. We map both to `_`
    so e.g. `claim/load-bearing` becomes `claim_load_bearing`. This is
    applied identically to the query body and the build_db `:create`, so
    the names always agree.
    """
    return raw.replace("/", "_").replace("-", "_")


def _relations_from_queries(queries: list[dict]) -> list[tuple[str, str, str]]:
    """Collect `(relation, value_col, value_type)` for every relation read by
    a query's :where, excluding the base `claim` relation. Relation names are
    sanitised to legal Cozo identifiers. Order-preserving and de-duplicated.
    """
    seen: dict[str, tuple[str, str, str]] = {}
    for q in queries:
        where = q.get(Keyword("where"), [])
        # First pass: collect numeric comparison bounds keyed by var name so
        # we can type a relation's var-valued column (e.g. `?p` in
        # `(claim/posterior ?claim ?p)` constrained by `(< ?p 0.8)`).
        var_types = _comparison_var_types(where)
        for clause in where:
            parsed = _parse_predicate_clause(clause)
            if parsed is None:
                continue
            raw_rel, value_term = parsed
            # Base/builtin detection on the RAW name: the `claim` base
            # relation is created by HEADER_TOP; a non-namespaced bare
            # predicate is a builtin, not a separate stored relation.
            if raw_rel == "claim" or "/" not in raw_rel:
                continue
            rel = _cozo_relation_name(raw_rel)
            if rel in seen:
                continue
            ty = _value_type(value_term, var_types)
            seen[rel] = (rel, "value", ty)
    return list(seen.values())


def _comparison_var_types(where: list) -> dict[str, str]:
    """Map var-name -> inferred type from comparison clauses like (< ?p 0.8)."""
    out: dict[str, str] = {}
    for clause in where:
        items = list(clause)
        if len(items) != 3:
            continue
        head = items[0]
        head_str = head.name if hasattr(head, "name") else str(head)
        if head_str not in {"<", ">", "<=", ">=", "=", "!="}:
            continue
        var = _var_name(items[1])
        if var is None:
            continue
        out[var] = _literal_type(items[2])
    return out


def _parse_predicate_clause(clause) -> tuple[str, Any] | None:
    """Return `(relation_name, second_arg)` for a predicate clause, else None.

    A predicate clause is `(pred arg0 arg1 ...)` where `pred` is a Symbol or
    Keyword (possibly namespaced). The value column is the second argument.
    Comparison clauses (`<`, `>`, ...) are not predicate clauses.
    """
    items = list(clause)
    if not items:
        return None
    head = items[0]
    head_str = head.name if hasattr(head, "name") else str(head)
    if head_str in {"<", ">", "<=", ">=", "=", "!="}:
        return None
    ns = getattr(head, "namespace", None)
    rel = f"{ns}/{head_str}" if ns else head_str
    value_term = items[2] if len(items) >= 3 else None
    return rel, value_term


def _var_name(term) -> str | None:
    """The bare name of a logic var (`?p` -> `?p`), else None for literals.

    Accepts both the bare-symbol surface form (`?p`) and the single-element
    wrapped form (`[?p]`) emitted by the EDN reader / used in tests.
    """
    from scripts._edn_reader import EdnList, EdnVector
    if isinstance(term, (list, EdnList, EdnVector)) and len(term) == 1:
        term = term[0]
    name = getattr(term, "name", None)
    if isinstance(name, str) and name.startswith("?"):
        return name
    # A logic var written without the leading `?` (e.g. Keyword("p")) still
    # denotes a binding position, not a literal value.
    if name is not None and not isinstance(term, (bool, int, float, str)):
        return name
    return None


def _literal_type(value: Any) -> str:
    if isinstance(value, bool):
        return "Bool"
    if isinstance(value, int):
        return "Int"
    if isinstance(value, float):
        return "Float"
    if isinstance(value, str):
        return "String"
    return "Float"


def _value_type(value_term: Any, var_types: dict[str, str]) -> str:
    """Infer the value column type from a clause's second arg.

    A literal types directly; a logic var is typed from a numeric comparison
    elsewhere in the :where, defaulting to Float when unconstrained.
    """
    var = _var_name(value_term)
    if var is not None:
        return var_types.get(var, "Float")
    if value_term is None:
        return "Float"
    return _literal_type(value_term)


def _require(q: dict, key: str) -> None:
    if Keyword(key) not in q:
        raise CodegenError(f"query {q.get(Keyword('id'))!r}: missing {key}")


def _emit_query_block(q: dict) -> str:
    qid       = q[Keyword("id")]
    on_result = q[Keyword("on-result")]
    defect    = on_result[Keyword("defect")]
    severity  = on_result[Keyword("severity")]
    script    = cozo_script_from_query(q)
    defect_name   = defect.name if isinstance(defect, Keyword) else str(defect)
    severity_name = severity.name if isinstance(severity, Keyword) else str(severity)
    label = f"{defect_name}/{severity_name}/{qid}"
    return (
        f'    // dispatch: "{qid}"\n'
        f"    {{\n"
        f"        let script = {_rust_string_literal(script)};\n"
        f"        let result: NamedRows = db.run_script(\n"
        f"            script, Default::default(), cozo::ScriptMutability::Immutable,\n"
        f"        ).map_err(|e| Error::Kg(format!({_rust_string_literal('query ' + qid + ': {e}')})))?;\n"
        f"        for row in result.rows.iter() {{\n"
        f"            // Each matched row produces a defect ({label}).\n"
        f"            let row_id = match row.first() {{\n"
        f"                Some(DataValue::Str(s)) => s.to_string(),\n"
        f"                _ => continue,\n"
        f"            }};\n"
        f"            contradictions.push((row_id, {_rust_string_literal(label)}.to_string()));\n"
        f"        }}\n"
        f"    }}\n"
    )


def _rust_string_literal(s: str) -> str:
    """Produce a Rust raw-string literal that survives any inner quotes."""
    hashes = "#"
    while ('"' + hashes) in s:
        hashes += "#"
    return f'r{hashes}"{s}"{hashes}'


def cozo_script_from_query(q: dict) -> str:
    """Render a defquery's :find/:where into Cozo Datalog syntax.

    Cozo syntax (simplified for v0.4):
      ?[var1, var2] := pred1[var1, var2], pred2[var1], var2 < 0.80
    """
    find  = q[Keyword("find")]
    where = q[Keyword("where")]
    head_vars = ", ".join(_render_term(t) for t in find)
    body      = ", ".join(_render_clause(c) for c in where)
    return f"?[{head_vars}] := {body}"


def _cozo_var(name: str) -> str:
    """Normalise a logic-var surface form to a Cozo variable name.

    EDN/Datalog writes logic vars with a leading `?` (`?claim`); Cozo
    variables are bare identifiers, so the sigil is stripped. Applied to
    both the `?[...]` head and the clause arguments so they bind the same
    name. REQ issue #141.
    """
    return name[1:] if name.startswith("?") else name


def _render_term(term: Any) -> str:
    from scripts._edn_reader import EdnList, EdnVector
    if isinstance(term, (list, EdnList, EdnVector)) and len(term) >= 1:
        sym = term[0]
        name = sym.name if isinstance(sym, Keyword) else str(sym)
        return _cozo_var(name)
    if isinstance(term, Keyword):
        return _cozo_var(term.name)
    return _cozo_var(str(term))


_COMPARISON_OPS = {"<", ">", "<=", ">=", "=", "!="}


def _render_clause(clause: list) -> str:
    head = clause[0]
    # Comparison clause: ('<' [var] 0.80). The operator may arrive as a bare
    # str, an EDN Symbol, or a Keyword; render it as a Cozo infix expression
    # (`p < 0.8`) rather than a relation atom.
    head_op = head if isinstance(head, str) else getattr(head, "name", None)
    if head_op in _COMPARISON_OPS:
        lhs = _render_term(clause[1])
        rhs = _render_value(clause[2])
        return f"{lhs} {head_op} {rhs}"
    # Predicate clause: (pred [args...] value)
    # Cozo stored-relation names are plain identifiers: a namespaced /
    # hyphenated EDN predicate (e.g. :claim/load-bearing) is sanitised to a
    # legal Cozo relation name (claim_load_bearing). The same sanitiser is
    # applied to the `:create` in build_db so the query references the
    # relation that actually exists. REQ issue #141.
    if isinstance(head, Keyword):
        # Reconstruct full name: namespace/name or just name
        raw = f"{head.namespace}/{head.name}" if head.namespace else head.name
    else:
        raw = str(head)
    pred = _cozo_relation_name(raw)
    from scripts._edn_reader import EdnList, EdnVector
    args = list(clause)[1:]
    rendered = []
    for a in args:
        if isinstance(a, (list, EdnList, EdnVector)) and len(a) == 1:
            rendered.append(_render_term(a))
        else:
            rendered.append(_render_value(a))
    inner = ", ".join(rendered)
    # `*` marks a read against a STORED relation (one created by `:create` in
    # build_db). Without it Cozo resolves the atom as an inline rule and
    # errors with "Requested rule ... not found". REQ issue #141.
    return f"*{pred}[{inner}]"


def _render_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return f"'{v}'"
    if isinstance(v, Keyword):
        # A keyword in value position denotes a logic var, not a literal.
        return _cozo_var(v.name)
    # Bare symbols (e.g. `?p`) are logic vars; strip the `?` sigil.
    return _cozo_var(str(v))


# ---------------------------------------------------------------- CLI

def run(project_root: Path) -> None:
    """End-to-end: read queries.edn, write kg.rs."""
    queries_path = project_root / "rules" / "queries.edn"
    kg_path      = project_root / "rust-verifier" / "src" / "kg.rs"
    if not queries_path.exists():
        return  # leave the stub
    payload = read_edn_file(queries_path)
    queries = payload.get(Keyword("queries"), [])
    src = generate_kg_source(queries)
    kg_path.parent.mkdir(parents=True, exist_ok=True)
    kg_path.write_text(src, encoding="utf-8", newline="\n")


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", required=True, type=Path)
    args = ap.parse_args(argv)
    run(args.project_root)
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(main(sys.argv[1:]))
