// GENERATED BY neurosym-forge codegen_axioms — DO NOT EDIT BY HAND.
// Edit rules/booklogic/constraints.edn instead, then run:
//   npm run codegen-axioms
//
// Source-of-truth: rules/constraints.edn (intermediate, emitted by
// `nbb -m {slug}.booklogic .`)
//
// Each `assert_and_track` call below corresponds to one `defconstraint`
// form. The tracker name equals the constraint id; on `solver.check()
// == Unsat`, `solver.get_unsat_core()` returns these names. Use
// `rules/axioms-tracker-map.edn` to translate them back to BookLogic
// ids and to the bound claim id.
//
// Constraints with :backend :egg discharge through the eqsat module
// (egg-rs 0.10); the resulting ProofResult is wrapped in a Z3 boolean
// tracker so unsat-core reporting keeps working uniformly.

#[cfg(feature = "smt")]
#[allow(unused_imports)]
use z3::{
    ast::{Array, Bool, Int, Real, Set, String as Z3String},
    Solver,
};
#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::str::FromStr as _;
#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::ops::{Add as _, Mul as _, Sub as _};

#[cfg(feature = "smt")]
/// Assert every z3 constraint whose `:assert` references exactly
/// the given `subject`. Cross-subject constraints are NOT asserted
/// here; they live in `axioms_shared`. Unknown subjects are a
/// no-op so the partition still runs `solver.check()` cleanly.
pub fn axioms_for_subject(solver: &Solver, subject: &str) {
    match subject {
        "s" => {
        // constraint C001-vant-hoff (approx-equality, relative tolerance 0.03)
        {
            let lhs = Real::new_const("osmotic-pressure-pa_s");
            let rhs = Real::new_const("vant-hoff-i_s").mul(&Real::new_const("molarity_s")).mul(&Real::from_rational(8314000, 1000000)).mul(&Real::new_const("temperature-k_s"));
            let diff = lhs.sub(&rhs);
            let eps  = Real::from_rational(30000, 1000000);
            let neg_eps = Real::from_rational(-30000, 1000000);
            let bound_pos = rhs.clone().mul(&eps);
            let bound_neg = rhs.clone().mul(&neg_eps);
            let upper_pos = diff.le(&bound_pos);
            let upper_neg = diff.le(&bound_neg);
            let lower_pos = bound_neg.le(&diff);
            let lower_neg = bound_pos.le(&diff);
            let bounded = Bool::and(&[
                &Bool::or(&[&upper_pos, &upper_neg]),
                &Bool::or(&[&lower_pos, &lower_neg]),
            ]);
            let tracker = Bool::new_const("C001-vant-hoff");
            solver.assert_and_track(&bounded, &tracker);
        }
        }
        _ => {
            let _ = solver;
        }
    }
}

#[cfg(not(feature = "smt"))]
pub fn axioms_for_subject(_solver: &(), _subject: &str) {
    // No-op: built without smt feature.
}

#[cfg(feature = "smt")]
/// Assert every z3 constraint whose `:assert` references two or
/// more distinct subjects (cross-subject constraints,
/// REQ-PERF-043). Also covers constraints with no subject
/// reference (pure-literal asserts) so those still run
/// unconditionally.
pub fn axioms_shared(solver: &Solver) {
    let _ = solver;
}

#[cfg(not(feature = "smt"))]
pub fn axioms_shared(_solver: &()) {
    // No-op: built without smt feature.
}

#[cfg(feature = "smt")]
/// Assert every z3 constraint declared with `:scope :corpus`
/// (REQ-CORPUS-050, 051). `smt::check_all` runs this once over a
/// solver seeded with the union of every subject's atoms, after
/// per-subject and shared partitions complete. A failed corpus
/// constraint surfaces on the verdict's `:corpus-defects` field.
pub fn axioms_corpus(solver: &Solver) {
    // constraint C050-trial-n-agrees
    {
        let lhs = Int::new_const("trial-n_mizuno-2008-chap-a");
        let rhs = Int::new_const("trial-n_mizuno-2008-chap-b");
        let tracker = Bool::new_const("C050-trial-n-agrees");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

}

#[cfg(not(feature = "smt"))]
pub fn axioms_corpus(_solver: &()) {
    // No-op: built without smt feature.
}

/// Enumerate every subject identifier (canonical form, e.g.
/// `"Bermuda"` or `"s"`) that has at least one declared
/// constraint. `smt::check_all` iterates this list to build
/// per-subject partitions deterministically.
pub fn axioms_subjects() -> &'static [&'static str] {
    &["s"]
}

/// REQ-CORPUS-053: every constraint id whose declared `:scope` is
/// `:corpus`. `smt::check_all` reads this to map unsat-core trackers
/// back to the constraint that drove the corpus-scope failure when
/// populating the verdict's `:corpus-defects` field.
pub fn axioms_corpus_ids() -> &'static [&'static str] {
    &["C050-trial-n-agrees"]
}

#[cfg(feature = "smt")]
/// Backward-compatible aggregator. Asserts every per-subject
/// constraint, the shared bucket, and any corpus-scope constraints
/// on a single solver. New callers should prefer
/// `axioms_for_subject` + `axioms_shared` + `axioms_corpus` so the
/// timeout and unknown blast-radius stays per-partition.
#[allow(dead_code)]
pub fn assert_axioms(solver: &Solver) {
    axioms_for_subject(solver, "s");
    axioms_shared(solver);
    axioms_corpus(solver);
}

#[cfg(not(feature = "smt"))]
pub fn assert_axioms(_solver: &()) {
    // No-op: built without smt feature.
}

#[cfg(feature = "smt")]
/// True if the named predicate-subject symbol should be bound as
/// `z3::ast::Real` rather than `z3::ast::Int`. The codegen promotes
/// a constraint subtree to Real whenever any float literal appears
/// anywhere in it; smt.rs uses this to keep value-bindings in the
/// same Z3 sort as the axioms reference.
#[allow(dead_code)]
pub fn predicate_is_real(name: &str) -> bool {
    match name {
        "molarity_s" => true,
        "osmotic-pressure-pa_s" => true,
        "temperature-k_s" => true,
        "vant-hoff-i_s" => true,
        _ => false,
    }
}

#[cfg(not(feature = "smt"))]
#[allow(dead_code)]
pub fn predicate_is_real(_name: &str) -> bool {
    false
}

#[cfg(feature = "smt")]
/// True if the named predicate-subject symbol carries a multi-valued
/// `[:vector <T>]` return-sort. smt.rs queries this to fail loudly
/// when an atom binds a scalar to a vector-typed predicate
/// (REQ-DSL-054).
pub fn predicate_is_vector(name: &str) -> bool {
    let _ = name; false
}

#[cfg(not(feature = "smt"))]
pub fn predicate_is_vector(_name: &str) -> bool {
    false
}

/// REQ-DATALOG-041: every `defconstraint :backend :cozo` form
/// surfaces here as a (name, datalog-source) pair. lib.rs runs
/// each pair through `kg::evaluate_constraint` and lifts a
/// non-empty row count into the verdict's `:cozo-defects` field.
pub fn cozo_constraints() -> Vec<(String, String)> {
    Vec::new()
}
