// GENERATED BY neurosym-forge codegen_axioms — DO NOT EDIT BY HAND.
// Edit rules/booklogic/constraints.edn instead, then run:
//   npm run codegen-axioms
//
// Source-of-truth: rules/constraints.edn (intermediate, emitted by
// `nbb -m {slug}.booklogic .`)
//
// Each `assert_and_track` call below corresponds to one `defconstraint`
// form. The tracker name equals the constraint id; on `solver.check()
// == Unsat`, `solver.get_unsat_core()` returns these names. Use
// `rules/axioms-tracker-map.edn` to translate them back to BookLogic
// ids and to the bound claim id.

#[cfg(feature = "smt")]
use z3::{
    ast::{Bool, Int, Real, String as Z3String},
    Solver,
};
#[cfg(feature = "smt")]
use std::str::FromStr as _;
#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::ops::{Add as _, Mul as _, Sub as _};

#[cfg(feature = "smt")]
pub fn assert_axioms(solver: &Solver) {
    // constraint C001-vant-hoff (approx-equality, tolerance 0.03)
    {
        let lhs = Real::new_const("osmotic-pressure-pa_s");
        let rhs = Real::new_const("vant-hoff-i_s").mul(&Real::new_const("molarity_s")).mul(&Real::from_rational(8314000, 1000000)).mul(&Real::new_const("temperature-k_s"));
        let diff = lhs.sub(&rhs);
        let eps  = Real::from_rational(30000, 1000000);
        let neg_eps = Real::from_rational(-30000, 1000000);
        let upper = diff.le(&eps);
        let lower = neg_eps.le(&diff);
        let bounded = Bool::and(&[&upper, &lower]);
        let tracker = Bool::new_const("C001-vant-hoff");
        solver.assert_and_track(&bounded, &tracker);
    }
}

#[cfg(not(feature = "smt"))]
pub fn assert_axioms(_solver: &()) {
    // No-op: built without smt feature.
}
