// GENERATED BY neurosym-forge codegen_axioms — DO NOT EDIT BY HAND.
// Edit rules/booklogic/constraints.edn instead, then run:
//   npm run codegen-axioms
//
// Source-of-truth: rules/constraints.edn (intermediate, emitted by
// `nbb -m {slug}.booklogic .`)
//
// Each `assert_and_track` call below corresponds to one `defconstraint`
// form. The tracker name equals the constraint id; on `solver.check()
// == Unsat`, `solver.get_unsat_core()` returns these names. Use
// `rules/axioms-tracker-map.edn` to translate them back to BookLogic
// ids and to the bound claim id.

#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::ops::{Add as _, Mul as _, Sub as _};
#[cfg(feature = "smt")]
use std::str::FromStr as _;
#[cfg(feature = "smt")]
use z3::{
    Solver,
    ast::{Bool, Int, Real, String as Z3String},
};

#[cfg(feature = "smt")]
pub fn assert_axioms(solver: &Solver) {
    // constraint C001-herd-immunity (approx-equality, relative tolerance 0.06)
    {
        let lhs =
            Real::new_const("vaccination-coverage_p").add(&Real::from_rational(500000, 1000000));
        let rhs =
            Real::new_const("herd-immunity-threshold_d").add(&Real::from_rational(500000, 1000000));
        let diff = lhs.sub(&rhs);
        let eps = Real::from_rational(60000, 1000000);
        let neg_eps = Real::from_rational(-60000, 1000000);
        let bound_pos = rhs.clone().mul(&eps);
        let bound_neg = rhs.clone().mul(&neg_eps);
        let upper_pos = diff.le(&bound_pos);
        let upper_neg = diff.le(&bound_neg);
        let lower_pos = bound_neg.le(&diff);
        let lower_neg = bound_pos.le(&diff);
        let bounded = Bool::and(&[
            &Bool::or(&[&upper_pos, &upper_neg]),
            &Bool::or(&[&lower_pos, &lower_neg]),
        ]);
        let tracker = Bool::new_const("C001-herd-immunity");
        solver.assert_and_track(&bounded, &tracker);
    }

    // constraint C002-threshold-formula (approx-equality, relative tolerance 0.05)
    {
        let lhs = Real::new_const("herd-immunity-threshold_d")
            .mul(&Real::new_const("basic-reproduction-number_d"))
            .add(&Real::from_rational(500000, 1000000));
        let rhs = Real::new_const("basic-reproduction-number_d")
            .sub(&Real::from_rational(1, 1))
            .add(&Real::from_rational(500000, 1000000));
        let diff = lhs.sub(&rhs);
        let eps = Real::from_rational(50000, 1000000);
        let neg_eps = Real::from_rational(-50000, 1000000);
        let bound_pos = rhs.clone().mul(&eps);
        let bound_neg = rhs.clone().mul(&neg_eps);
        let upper_pos = diff.le(&bound_pos);
        let upper_neg = diff.le(&bound_neg);
        let lower_pos = bound_neg.le(&diff);
        let lower_neg = bound_pos.le(&diff);
        let bounded = Bool::and(&[
            &Bool::or(&[&upper_pos, &upper_neg]),
            &Bool::or(&[&lower_pos, &lower_neg]),
        ]);
        let tracker = Bool::new_const("C002-threshold-formula");
        solver.assert_and_track(&bounded, &tracker);
    }
}

#[cfg(not(feature = "smt"))]
pub fn assert_axioms(_solver: &()) {
    // No-op: built without smt feature.
}

#[cfg(feature = "smt")]
/// True if the named predicate-subject symbol should be bound as
/// `z3::ast::Real` rather than `z3::ast::Int`. The codegen promotes
/// a constraint subtree to Real whenever any float literal appears
/// anywhere in it; smt.rs uses this to keep value-bindings in the
/// same Z3 sort as the axioms reference.
pub fn predicate_is_real(name: &str) -> bool {
    match name {
        "basic-reproduction-number_d" => true,
        "herd-immunity-threshold_d" => true,
        "vaccination-coverage_p" => true,
        _ => false,
    }
}

#[cfg(not(feature = "smt"))]
pub fn predicate_is_real(_name: &str) -> bool {
    false
}
