"""Render a bipartite consensus map (schools × rules) as TikZ + SVG."""
from __future__ import annotations
import argparse
import sys
from pathlib import Path
from ._positions_io import Position, read_positions
from ._stance import Stance
from .._staleness import check_positions_fresh


_STANCE_COLOUR = {
    Stance.SUPPORTS:    "green",
    Stance.CONTRADICTS: "red",
    Stance.EXTENDS:     "blue",
    Stance.SILENT:      "gray",
}


def _emit_tikz(positions: list[Position]) -> str:
    schools = sorted({p.school for p in positions})
    rules = sorted({p.rule_id for p in positions})
    lines = [
        "% Generated by syntopical-metabook render_consensus_map — DO NOT EDIT.",
        r"\begin{tikzpicture}[node distance=1.4cm, every node/.style={font=\small}]",
    ]
    for i, s in enumerate(schools):
        safe = s.replace("-", "_")
        lines.append(rf"  \node (school_{safe}) at (0, -{i}) {{\textbf{{{s}}}}};")
    for i, r in enumerate(rules):
        safe = r.replace("/", "_").replace(":", "").replace("-", "_")
        lines.append(rf"  \node (rule_{safe}) at (5, -{i}) {{\texttt{{{r}}}}};")
    for p in sorted(positions, key=lambda x: (x.school, x.rule_id)):
        if p.stance == Stance.SILENT:
            continue
        s_safe = p.school.replace("-", "_")
        r_safe = p.rule_id.replace("/", "_").replace(":", "").replace("-", "_")
        colour = _STANCE_COLOUR[p.stance]
        lines.append(
            rf"  \draw[->, {colour}] (school_{s_safe}) -- (rule_{r_safe});"
        )
    lines.append(r"\end{tikzpicture}")
    return "\n".join(lines) + "\n"


def _emit_svg(positions: list[Position]) -> str:
    schools = sorted({p.school for p in positions})
    rules = sorted({p.rule_id for p in positions})
    row_h = 30
    width = 600
    height = max(len(schools), len(rules)) * row_h + 40
    body = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">']
    for i, s in enumerate(schools):
        y = 20 + i * row_h
        body.append(f'<text x="10" y="{y}" font-family="sans-serif" font-size="14" font-weight="bold">{s}</text>')
    for i, r in enumerate(rules):
        y = 20 + i * row_h
        body.append(f'<text x="400" y="{y}" font-family="monospace" font-size="12">{r}</text>')
    school_idx = {s: i for i, s in enumerate(schools)}
    rule_idx = {r: i for i, r in enumerate(rules)}
    for p in sorted(positions, key=lambda x: (x.school, x.rule_id)):
        if p.stance == Stance.SILENT:
            continue
        sy = 16 + school_idx[p.school] * row_h
        ry = 16 + rule_idx[p.rule_id] * row_h
        colour = {
            Stance.SUPPORTS: "#22c55e",
            Stance.CONTRADICTS: "#ef4444",
            Stance.EXTENDS: "#3b82f6",
        }[p.stance]
        body.append(
            f'<line x1="100" y1="{sy}" x2="390" y2="{ry}" '
            f'stroke="{colour}" stroke-width="1.5" />'
        )
    body.append("</svg>")
    return "\n".join(body) + "\n"


def render_consensus_map(positions_path: Path, out_dir: Path) -> dict[str, Path]:
    check_positions_fresh(positions_path)
    positions = read_positions(positions_path)
    out_dir.mkdir(parents=True, exist_ok=True)
    tex_path = out_dir / "consensus-map.tex"
    svg_path = out_dir / "consensus-map.svg"
    tex_path.write_text(_emit_tikz(positions), encoding="utf-8", newline="\n")
    svg_path.write_text(_emit_svg(positions), encoding="utf-8", newline="\n")
    return {"tex": tex_path, "svg": svg_path}


def _main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="python -m scripts.governance.render_consensus_map")
    ap.add_argument("workspace", type=Path)
    args = ap.parse_args(argv)
    workspace = args.workspace.resolve()
    paths = render_consensus_map(
        workspace / "syntopical" / "positions.edn",
        workspace / "syntopical" / "figures",
    )
    print(f"wrote {paths['tex']} + {paths['svg']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
