"""Generate rust-verifier/src/kg.rs from rules/queries.edn.

REQ-DSL-031: kg.rs runs compiled queries via Cozo and returns row vectors.

Each defquery becomes:
  - a Cozo script (Datalog syntax)
  - a dispatch entry in `ingest_and_summarize` that runs the script
    against the claim graph and pushes any returned row as a defect

The intermediate `rules/queries.edn` is written by booklogic.cljs.tmpl's
emit-queries-edn; this module reads it and emits Rust source.

Cozo is embedded; we use `cozo::DbInstance::new("mem", "", "")` for the
in-memory backend. The graph is populated at verifier startup from the
incoming claims; the queries run as a Phase-2 sweep after the SMT walk.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from scripts._edn_reader import Keyword
from scripts._io import read_edn_file


class CodegenError(ValueError):
    """Raised when a query is malformed for kg codegen."""


SUPPORTED_BACKENDS = {Keyword("cozo")}

HEADER = """\
// GENERATED BY neurosym-forge codegen_kg — DO NOT EDIT BY HAND.
// Edit rules/booklogic/queries.edn instead, then run:
//   npm run codegen-kg
//
// One Cozo script per defquery; each runs at verification time against
// an in-memory claim graph populated from the incoming claims slice.

use crate::ir::{Claim, GraphSummary, Error};

#[cfg(feature = "kg")]
use cozo::{DbInstance, DataValue, NamedRows};

#[cfg(feature = "kg")]
fn build_db(claims: &[Claim]) -> Result<DbInstance, Error> {
    let db = DbInstance::new("mem", "", "")
        .map_err(|e| Error::Kg(format!("cozo init: {e}")))?;
    // Populate a minimal `claim {id, source}` relation; expand as the
    // schema grows. v0.4 only models the two ir::Claim fields.
    db.run_script(
        ":create claim {id: String => source: String}",
        Default::default(),
        cozo::ScriptMutability::Mutable,
    ).map_err(|e| Error::Kg(format!("cozo create: {e}")))?;
    for c in claims {
        let script = format!(
            "?[id, source] <- [['{}', '{}']] :put claim {{id, source}}",
            c.id.replace("'", "\\\\'"),
            c.source.replace("'", "\\\\'"),
        );
        db.run_script(&script, Default::default(), cozo::ScriptMutability::Mutable)
            .map_err(|e| Error::Kg(format!("cozo insert: {e}")))?;
    }
    Ok(db)
}

#[cfg(feature = "kg")]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    let db = build_db(claims)?;
    let mut contradictions: Vec<(String, String)> = Vec::new();
"""

FOOTER = """\
    Ok(GraphSummary {
        claim_count: claims.len(),
        contradictions,
    })
}

#[cfg(not(feature = "kg"))]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    Ok(GraphSummary { claim_count: claims.len(), contradictions: vec![] })
}
"""


def generate_kg_source(queries: list[dict]) -> str:
    """Emit a complete kg.rs file from a list of query dicts."""
    body_lines: list[str] = []
    for q in queries:
        _require(q, "id")
        _require(q, "backend")
        backend = q[Keyword("backend")]
        if backend not in SUPPORTED_BACKENDS:
            raise CodegenError(
                f"query {q.get(Keyword('id'))!r}: unknown backend {backend!r}; "
                f"expected one of {SUPPORTED_BACKENDS}"
            )
        body_lines.append(_emit_query_block(q))
    body = "\n".join(body_lines) if body_lines else "    // no queries declared\n"
    return HEADER + body + FOOTER


def _require(q: dict, key: str) -> None:
    if Keyword(key) not in q:
        raise CodegenError(f"query {q.get(Keyword('id'))!r}: missing {key}")


def _emit_query_block(q: dict) -> str:
    qid       = q[Keyword("id")]
    on_result = q[Keyword("on-result")]
    defect    = on_result[Keyword("defect")]
    severity  = on_result[Keyword("severity")]
    script    = cozo_script_from_query(q)
    defect_name   = defect.name if isinstance(defect, Keyword) else str(defect)
    severity_name = severity.name if isinstance(severity, Keyword) else str(severity)
    label = f"{defect_name}/{severity_name}/{qid}"
    return (
        f'    // dispatch: "{qid}"\n'
        f"    {{\n"
        f"        let script = {_rust_string_literal(script)};\n"
        f"        let result: NamedRows = db.run_script(\n"
        f"            script, Default::default(), cozo::ScriptMutability::Immutable,\n"
        f"        ).map_err(|e| Error::Kg(format!({_rust_string_literal('query ' + qid + ': {e}')})))?;\n"
        f"        for row in result.rows.iter() {{\n"
        f"            // Each matched row produces a defect ({label}).\n"
        f"            let row_id = match row.first() {{\n"
        f"                Some(DataValue::Str(s)) => s.to_string(),\n"
        f"                _ => continue,\n"
        f"            }};\n"
        f"            contradictions.push((row_id, {_rust_string_literal(label)}.to_string()));\n"
        f"        }}\n"
        f"    }}\n"
    )


def _rust_string_literal(s: str) -> str:
    """Produce a Rust raw-string literal that survives any inner quotes."""
    hashes = "#"
    while ('"' + hashes) in s:
        hashes += "#"
    return f'r{hashes}"{s}"{hashes}'


def cozo_script_from_query(q: dict) -> str:
    """Render a defquery's :find/:where into Cozo Datalog syntax.

    Cozo syntax (simplified for v0.4):
      ?[var1, var2] := pred1[var1, var2], pred2[var1], var2 < 0.80
    """
    find  = q[Keyword("find")]
    where = q[Keyword("where")]
    head_vars = ", ".join(_render_term(t) for t in find)
    body      = ", ".join(_render_clause(c) for c in where)
    return f"?[{head_vars}] := {body}"


def _render_term(term: Any) -> str:
    from scripts._edn_reader import EdnList, EdnVector
    if isinstance(term, (list, EdnList, EdnVector)) and len(term) >= 1:
        sym = term[0]
        return sym.name if isinstance(sym, Keyword) else str(sym)
    if isinstance(term, Keyword):
        return term.name
    return str(term)


def _render_clause(clause: list) -> str:
    head = clause[0]
    # Comparison clause: ('<' [var] 0.80)
    if isinstance(head, str) and head in {"<", ">", "<=", ">=", "=", "!="}:
        lhs = _render_term(clause[1])
        rhs = _render_value(clause[2])
        return f"{lhs} {head} {rhs}"
    # Predicate clause: (pred [args...] value)
    # For keywords, preserve namespace with slash (e.g. :claim/load-bearing → claim/load-bearing)
    if isinstance(head, Keyword):
        # Reconstruct full name: namespace/name or just name
        pred = f"{head.namespace}/{head.name}" if head.namespace else head.name
    else:
        pred = str(head)
    from scripts._edn_reader import EdnList, EdnVector
    args = list(clause)[1:]
    rendered = []
    for a in args:
        if isinstance(a, (list, EdnList, EdnVector)) and len(a) == 1:
            rendered.append(_render_term(a))
        else:
            rendered.append(_render_value(a))
    inner = ", ".join(rendered)
    return f"{pred}[{inner}]"


def _render_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return f"'{v}'"
    if isinstance(v, Keyword):
        return v.name
    return str(v)


# ---------------------------------------------------------------- CLI

def run(project_root: Path) -> None:
    """End-to-end: read queries.edn, write kg.rs."""
    queries_path = project_root / "rules" / "queries.edn"
    kg_path      = project_root / "rust-verifier" / "src" / "kg.rs"
    if not queries_path.exists():
        return  # leave the stub
    payload = read_edn_file(queries_path)
    queries = payload.get(Keyword("queries"), [])
    src = generate_kg_source(queries)
    kg_path.parent.mkdir(parents=True, exist_ok=True)
    kg_path.write_text(src, encoding="utf-8", newline="\n")


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", required=True, type=Path)
    args = ap.parse_args(argv)
    run(args.project_root)
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(main(sys.argv[1:]))
