// GENERATED BY neurosym-forge codegen_axioms — DO NOT EDIT BY HAND.
// Edit rules/booklogic/constraints.edn instead, then run:
//   npm run codegen-axioms
//
// Source-of-truth: rules/constraints.edn (intermediate, emitted by
// `nbb -m {slug}.booklogic .`)
//
// Each `assert_and_track` call below corresponds to one `defconstraint`
// form. The tracker name equals the constraint id; on `solver.check()
// == Unsat`, `solver.get_unsat_core()` returns these names. Use
// `rules/axioms-tracker-map.edn` to translate them back to BookLogic
// ids and to the bound claim id.

#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::ops::{Add as _, Mul as _, Sub as _};
#[cfg(feature = "smt")]
use std::str::FromStr as _;
#[cfg(feature = "smt")]
use z3::{
    Solver,
    ast::{Bool, Int, Real, String as Z3String},
};

#[cfg(feature = "smt")]
pub fn assert_axioms(solver: &Solver) {
    // constraint C001-bermuda-parishes
    {
        let lhs = Int::new_const("parishes-count_Bermuda");
        let rhs = Int::from_i64(9);
        let tracker = Bool::new_const("C001-bermuda-parishes");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C002-named-islands-and-rocks
    {
        let lhs = Int::new_const("named-islands-and-rocks_Bermuda");
        let rhs = Int::from_i64(181);
        let tracker = Bool::new_const("C002-named-islands-and-rocks");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C003-bmd-usd-parity
    {
        let lhs = Bool::new_const("currency-pegged-at-parity_BMD");
        let rhs = Bool::from_bool(true);
        let tracker = Bool::new_const("C003-bmd-usd-parity");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C004-airport-st-davids
    {
        let lhs = Z3String::new_const("airport-on-island_L_F_Wade");
        let rhs = Z3String::from_str("St_Davids_Island").expect("valid utf-8");
        let tracker = Bool::new_const("C004-airport-st-davids");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C005-cedar-binomial
    {
        let lhs = Z3String::new_const("binomial_Bermuda_cedar");
        let rhs = Z3String::from_str("Juniperus bermudiana").expect("valid utf-8");
        let tracker = Bool::new_const("C005-cedar-binomial");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C006-population
    {
        let lhs = Int::new_const("population_Bermuda");
        let rhs = Int::from_i64(63918);
        let tracker = Bool::new_const("C006-population");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C007-land-area-km2
    {
        let lhs = Real::new_const("land-area-km2_Bermuda");
        let rhs = Real::from_rational(53200000, 1000000);
        let tracker = Bool::new_const("C007-land-area-km2");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C008-gdp-usd-billion
    {
        let lhs = Real::new_const("gdp-usd-billion_Bermuda");
        let rhs = Real::from_rational(7700000, 1000000);
        let tracker = Bool::new_const("C008-gdp-usd-billion");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C009-hospital-beds-kemh
    {
        let lhs = Int::new_const("hospital-beds-kemh_KEMH");
        let rhs = Int::from_i64(90);
        let tracker = Bool::new_const("C009-hospital-beds-kemh");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }
}

#[cfg(not(feature = "smt"))]
pub fn assert_axioms(_solver: &()) {
    // No-op: built without smt feature.
}
