// GENERATED BY neurosym-forge codegen_axioms — DO NOT EDIT BY HAND.
// Edit rules/booklogic/constraints.edn instead, then run:
//   npm run codegen-axioms
//
// Source-of-truth: rules/constraints.edn (intermediate, emitted by
// `nbb -m {slug}.booklogic .`)
//
// Each `assert_and_track` call below corresponds to one `defconstraint`
// form. The tracker name equals the constraint id; on `solver.check()
// == Unsat`, `solver.get_unsat_core()` returns these names. Use
// `rules/axioms-tracker-map.edn` to translate them back to BookLogic
// ids and to the bound claim id.
//
// Constraints with :backend :egg discharge through the eqsat module
// (egg-rs 0.10); the resulting ProofResult is wrapped in a Z3 boolean
// tracker so unsat-core reporting keeps working uniformly.

#[cfg(feature = "smt")]
#[allow(unused_imports)]
use z3::{
    ast::{Array, Bool, Int, Real, Set, String as Z3String},
    Solver,
};
#[cfg(feature = "smt")]
use std::str::FromStr as _;
#[cfg(feature = "smt")]
#[allow(unused_imports)]
use std::ops::{Add as _, Mul as _, Sub as _};

#[cfg(feature = "smt")]
pub fn assert_axioms(solver: &Solver) {
    // constraint C001-bermuda-parishes
    {
        let lhs = Int::new_const("parishes-count_Bermuda");
        let rhs = Int::from_i64(9);
        let tracker = Bool::new_const("C001-bermuda-parishes");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C002-named-islands-and-rocks
    {
        let lhs = Int::new_const("named-islands-and-rocks_Bermuda");
        let rhs = Int::from_i64(181);
        let tracker = Bool::new_const("C002-named-islands-and-rocks");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C003-bmd-usd-parity
    {
        let lhs = Bool::new_const("currency-pegged-at-parity_BMD");
        let rhs = Bool::from_bool(true);
        let tracker = Bool::new_const("C003-bmd-usd-parity");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C004-airport-st-davids
    {
        let lhs = Z3String::new_const("airport-on-island_L_F_Wade");
        let rhs = Z3String::from_str("St_Davids_Island").expect("valid utf-8");
        let tracker = Bool::new_const("C004-airport-st-davids");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C005-cedar-binomial
    {
        let lhs = Z3String::new_const("binomial_Bermuda_cedar");
        let rhs = Z3String::from_str("Juniperus bermudiana").expect("valid utf-8");
        let tracker = Bool::new_const("C005-cedar-binomial");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C006-population
    {
        let lhs = Int::new_const("population_Bermuda");
        let rhs = Int::from_i64(63918);
        let tracker = Bool::new_const("C006-population");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C007-land-area-km2
    {
        let lhs = Real::new_const("land-area-km2_Bermuda");
        let rhs = Real::from_rational(53200000, 1000000);
        let tracker = Bool::new_const("C007-land-area-km2");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C008-gdp-usd-billion
    {
        let lhs = Real::new_const("gdp-usd-billion_Bermuda");
        let rhs = Real::from_rational(7700000, 1000000);
        let tracker = Bool::new_const("C008-gdp-usd-billion");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }

    // constraint C009-hospital-beds-kemh
    {
        let lhs = Int::new_const("hospital-beds-kemh_KEMH");
        let rhs = Int::from_i64(90);
        let tracker = Bool::new_const("C009-hospital-beds-kemh");
        solver.assert_and_track(&lhs.eq(&rhs), &tracker);
    }
}

#[cfg(not(feature = "smt"))]
pub fn assert_axioms(_solver: &()) {
    // No-op: built without smt feature.
}

#[cfg(feature = "smt")]
/// True if the named predicate-subject symbol should be bound as
/// `z3::ast::Real` rather than `z3::ast::Int`. The codegen promotes
/// a constraint subtree to Real whenever any float literal appears
/// anywhere in it; smt.rs uses this to keep value-bindings in the
/// same Z3 sort as the axioms reference.
pub fn predicate_is_real(name: &str) -> bool {
    match name {
        "gdp-usd-billion_Bermuda" => true,
        "land-area-km2_Bermuda" => true,
        _ => false,
    }
}

#[cfg(not(feature = "smt"))]
pub fn predicate_is_real(_name: &str) -> bool {
    false
}

#[cfg(feature = "smt")]
/// True if the named predicate-subject symbol carries a multi-valued
/// `[:vector <T>]` return-sort. smt.rs queries this to fail loudly
/// when an atom binds a scalar to a vector-typed predicate
/// (REQ-DSL-054).
pub fn predicate_is_vector(name: &str) -> bool {
    let _ = name; false
}

#[cfg(not(feature = "smt"))]
pub fn predicate_is_vector(_name: &str) -> bool {
    false
}

/// REQ-DATALOG-041: every `defconstraint :backend :cozo` form
/// surfaces here as a (name, datalog-source) pair. lib.rs runs
/// each pair through `kg::evaluate_constraint` and lifts a
/// non-empty row count into the verdict's `:cozo-defects` field.
pub fn cozo_constraints() -> Vec<(String, String)> {
    Vec::new()
}
