// GENERATED BY neurosym-forge codegen_kg — DO NOT EDIT BY HAND.
// Edit rules/booklogic/queries.edn instead, then run:
//   npm run codegen-kg
//
// One Cozo script per defquery; each runs at verification time against
// an in-memory claim graph populated from the incoming claims slice.

use crate::ir::{Claim, Error, GraphSummary};

#[cfg(feature = "kg")]
use cozo::{DataValue, DbInstance, NamedRows};

#[cfg(feature = "kg")]
fn build_db(claims: &[Claim]) -> Result<DbInstance, Error> {
    let db = DbInstance::new("mem", "", "").map_err(|e| Error::Kg(format!("cozo init: {e}")))?;
    // Populate a minimal `claim {id, source}` relation; expand as the
    // schema grows. v0.4 only models the two ir::Claim fields.
    db.run_script(
        ":create claim {id: String => source: String}",
        Default::default(),
        cozo::ScriptMutability::Mutable,
    )
    .map_err(|e| Error::Kg(format!("cozo create: {e}")))?;
    for c in claims {
        let script = format!(
            "?[id, source] <- [['{}', '{}']] :put claim {{id, source}}",
            c.id.replace("'", "\\'"),
            c.source.replace("'", "\\'"),
        );
        db.run_script(&script, Default::default(), cozo::ScriptMutability::Mutable)
            .map_err(|e| Error::Kg(format!("cozo insert: {e}")))?;
    }
    Ok(db)
}

#[cfg(feature = "kg")]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    let db = build_db(claims)?;
    let mut contradictions: Vec<(String, String)> = Vec::new();
    // dispatch: "Q001-low-confidence-load-bearing"
    {
        let script = r#"?[?claim] := claim/load-bearing[?claim, true], claim/posterior[?claim, ?p], <[?p, 0.8]"#;
        let result: NamedRows = db
            .run_script(
                script,
                Default::default(),
                cozo::ScriptMutability::Immutable,
            )
            .map_err(|e| Error::Kg(format!(r#"query Q001-low-confidence-load-bearing: {e}"#)))?;
        for row in result.rows.iter() {
            // Each matched row produces a defect (posterior-floor/warning/Q001-low-confidence-load-bearing).
            let row_id = match row.first() {
                Some(DataValue::Str(s)) => s.to_string(),
                _ => continue,
            };
            contradictions.push((
                row_id,
                r#"posterior-floor/warning/Q001-low-confidence-load-bearing"#.to_string(),
            ));
        }
    }
    Ok(GraphSummary {
        claim_count: claims.len(),
        contradictions,
    })
}

#[cfg(not(feature = "kg"))]
pub fn ingest_and_summarize(claims: &[Claim]) -> Result<GraphSummary, Error> {
    Ok(GraphSummary {
        claim_count: claims.len(),
        contradictions: vec![],
    })
}
