"""Local PDF ingest using pdfplumber. No external API."""
from __future__ import annotations

import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import pdfplumber

from .ingest_common import append_log_entry
from .source_manifest import compute_doc_id, compute_sha256, write_manifest
from .workspace import WorkspaceLayout, find_workspace_root


_HEADING_HINT = re.compile(r"^\s*(Chapter|Section|Part|Appendix)\s+", re.IGNORECASE)


def _detect_chapter_lines(pages_text: list[str]) -> list[dict]:
    nodes: list[dict] = []
    for idx, text in enumerate(pages_text, start=1):
        first_line = (text or "").splitlines()[0] if text else ""
        if first_line and _HEADING_HINT.match(first_line):
            nodes.append({"page": idx, "title": first_line.strip()})
    return nodes


def _build_summary(doc_id: str, pages_text: list[str], nodes: list[dict]) -> str:
    lines = [
        f"# Source — {doc_id}",
        "",
        f"_Auto-generated by book-knowledge ingest. {len(pages_text)} pages, {len(nodes)} structural nodes._",
        "",
        "## Page-by-page extracts",
        "",
    ]
    for idx, text in enumerate(pages_text, start=1):
        lines.append(f"### Page {idx}")
        lines.append("")
        snippet = (text or "").strip().replace("\n", " ")
        if len(snippet) > 400:
            snippet = snippet[:400].rstrip() + "..."
        lines.append(f"> {snippet}")
        lines.append("")
    if nodes:
        lines.append("## Detected structural nodes")
        lines.append("")
        for n in nodes:
            lines.append(f"- p{n['page']}: {n['title']}")
    return "\n".join(lines) + "\n"


def ingest_pdf(source_path: Path, workspace: Path) -> dict:
    src = Path(source_path).resolve()
    ws_root = workspace if (workspace / "CLAUDE.md").is_file() else find_workspace_root(workspace)
    if ws_root is None:
        raise ValueError(f"no workspace found at {workspace}")
    layout = WorkspaceLayout(ws_root)

    doc_id = compute_doc_id(src.name)
    sha = compute_sha256(src)

    pages_text: list[str] = []
    with pdfplumber.open(str(src)) as pdf:
        for page in pdf.pages:
            pages_text.append(page.extract_text() or "")

    nodes = _detect_chapter_lines(pages_text)

    raw_dest = layout.raw_pdf / src.name
    if not raw_dest.exists():
        shutil.copy(src, raw_dest)

    manifest = {
        "doc_name": src.name,
        "doc_id": doc_id,
        "source_kind": "pdf",
        "sha256": sha,
        "byte_size": src.stat().st_size,
        "ingested_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "page_count": len(pages_text),
        "node_count": len(nodes) if nodes else len(pages_text),
        "tree_root": "doc",
    }
    write_manifest(layout.manifests / f"{doc_id}.json", manifest)

    summary = _build_summary(doc_id, pages_text, nodes)
    (layout.wiki_sources / f"{doc_id}.md").write_text(summary, encoding="utf-8")

    append_log_entry(layout, "ingest-pdf", doc_id,
                     f"- Added source summary covering {len(pages_text)} pages, {len(nodes)} structural nodes")

    return manifest


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print("usage: ingest_pdf.py <source.pdf> <workspace-dir>", file=sys.stderr)
        return 2
    result = ingest_pdf(Path(argv[1]), Path(argv[2]))
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
