"""Local markdown ingest — heading-tree extraction via markdown-it-py."""
from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from markdown_it import MarkdownIt

from .ingest_common import append_log_entry
from .source_manifest import compute_doc_id, compute_sha256, write_manifest
from .workspace import WorkspaceLayout, find_workspace_root


def _heading_tree(text: str) -> list[dict]:
    md = MarkdownIt()
    tokens = md.parse(text)
    nodes: list[dict] = []
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok.type == "heading_open":
            level = int(tok.tag[1])
            inline = tokens[i + 1]
            nodes.append({"level": level, "title": inline.content})
            i += 3
        else:
            i += 1
    return nodes


def _build_summary(doc_id: str, headings: list[dict], byte_count: int) -> str:
    lines = [
        f"# Source — {doc_id}",
        "",
        f"_Auto-generated by book-knowledge ingest. {byte_count} bytes._",
        "",
        "## Heading tree",
        "",
    ]
    for h in headings:
        prefix = "  " * (h["level"] - 1)
        lines.append(f"{prefix}- {h['title']}")
    return "\n".join(lines) + "\n"


def ingest_markdown(source_path: Path, workspace: Path) -> dict:
    src = Path(source_path).resolve()
    ws_root = workspace if (workspace / "CLAUDE.md").is_file() else find_workspace_root(workspace)
    if ws_root is None:
        raise ValueError(f"no workspace found at {workspace}")
    layout = WorkspaceLayout(ws_root)
    text = src.read_text(encoding="utf-8")

    doc_id = compute_doc_id(src.name)
    sha = compute_sha256(src)
    headings = _heading_tree(text)

    raw_dest = layout.raw_markdown / src.name
    if not raw_dest.exists():
        shutil.copy(src, raw_dest)

    manifest = {
        "doc_name": src.name,
        "doc_id": doc_id,
        "source_kind": "markdown",
        "sha256": sha,
        "byte_size": src.stat().st_size,
        "ingested_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "node_count": len(headings),
        "page_count": 0,
        "tree_root": "doc",
    }
    write_manifest(layout.manifests / f"{doc_id}.json", manifest)

    summary = _build_summary(doc_id, headings, src.stat().st_size)
    (layout.wiki_sources / f"{doc_id}.md").write_text(summary, encoding="utf-8")

    append_log_entry(layout, "ingest-markdown", doc_id,
                     f"- Added source summary with {len(headings)} headings")

    return manifest


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print("usage: ingest_markdown.py <source.md> <workspace-dir>", file=sys.stderr)
        return 2
    result = ingest_markdown(Path(argv[1]), Path(argv[2]))
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
