"""Rebuild wiki/index.md from the wiki tree."""
from __future__ import annotations

import sys
from pathlib import Path

from .workspace import WorkspaceLayout

SECTIONS = [
    ("Sources",  "sources"),
    ("Concepts", "concepts"),
    ("Entities", "entities"),
    ("Chapters", "chapters"),
]


def _list_pages(directory: Path) -> list[str]:
    if not directory.is_dir():
        return []
    return sorted(p.stem for p in directory.glob("*.md"))


def wiki_index_regen(layout: WorkspaceLayout) -> Path:
    lines = ["# Wiki Index", "",
             "_Regenerated by `wiki_index_regen.py` after every ingest._", ""]
    for label, sub in SECTIONS:
        lines.append(f"## {label}")
        lines.append("")
        pages = _list_pages(layout.wiki / sub)
        if pages:
            for name in pages:
                lines.append(f"- [{name}]({sub}/{name}.md)")
        else:
            lines.append("_(empty)_")
        lines.append("")
    layout.wiki_index.write_text("\n".join(lines), encoding="utf-8")
    return layout.wiki_index


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: wiki_index_regen.py <workspace-dir>", file=sys.stderr)
        return 2
    layout = WorkspaceLayout(Path(argv[1]))
    wiki_index_regen(layout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
