# skills/neurosym-forge/tests/test_codegen_axioms.py
"""Tests for codegen_axioms: generate axioms.rs + tracker map.

REQ-DSL-021: axioms.rs codegen with assert_and_track per constraint.
REQ-DSL-022: ~= (approximate-equality) operator desugaring.
REQ-DSL-023: axioms-tracker-map.edn bidirectional traceability.
REQ-VERIFIER-BUILD-010: byte-deterministic output.
"""
from __future__ import annotations

from pathlib import Path
import pytest

from scripts.codegen_axioms import (
    generate_axioms_source,
    generate_tracker_map,
    CodegenError,
)
from scripts._edn_reader import Keyword


def _constraint(name="C001",
                backend=":z3",
                assert_form="(= (:parishes-count :Bermuda) 9)",
                tolerance=None,
                track=":claim/id",
                defect=":D13",
                severity=":critical",
                message="parish count off"):
    return {
        Keyword("id"):        name,
        Keyword("backend"):   Keyword(backend.lstrip(":")),
        Keyword("assert"):    assert_form,            # stored as EDN-printed string
        Keyword("tolerance"): tolerance,
        Keyword("track"):     Keyword(track.lstrip(":").replace("/", "_")) if track.startswith(":") else track,
        Keyword("on-unsat"):  {
            Keyword("defect"):   Keyword(defect.lstrip(":")),
            Keyword("severity"): Keyword(severity.lstrip(":")),
            Keyword("message"):  message,
        },
    }


def test_generate_simple_z3_int_constraint() -> None:
    """REQ-DSL-021: basic z3 constraint produces assert_and_track."""
    cs = [_constraint(name="C001", assert_form="(= (:parishes-count :Bermuda) 9)")]
    src = generate_axioms_source(cs)
    assert "// GENERATED BY neurosym-forge codegen_axioms" in src
    assert "pub fn assert_axioms" in src
    assert "assert_and_track" in src
    # Tracker name uses the constraint id when no claim binding exists.
    assert '"C001"' in src


def test_generate_approx_equality_emits_tolerance_clamp() -> None:
    """REQ-DSL-022: ~= desugars to |a - b| <= tolerance."""
    cs = [_constraint(name="C002",
                      assert_form="(~= (:osmotic-pressure-pa :sample) (* (:vant-hoff-i :sample) 8.314) :tolerance 0.03)",
                      tolerance=0.03)]
    src = generate_axioms_source(cs)
    # |a - b| <= ε desugaring lives in the emitted source as a Real difference + le.
    assert "0.03" in src
    assert "tolerance" in src.lower() or "approx" in src.lower()


def test_generate_multiple_constraints_each_tracked_uniquely() -> None:
    """REQ-DSL-021: each constraint gets its own tracker."""
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src = generate_axioms_source(cs)
    assert src.count("assert_and_track") >= 2
    assert '"C001"' in src
    assert '"C002"' in src


def test_predicate_is_real_helper_lists_promoted_predicates() -> None:
    """REQ-DSL-024: codegen emits `predicate_is_real(name)` enumerating
    every predicate-subject symbol that ended up Real-typed (because some
    sibling subexpression contained a float literal). smt.rs queries this
    to pick the matching Z3 sort for value-bindings; without it, axioms
    referencing `Real::new_const("vant-hoff-i_s")` and value-bindings
    using `Int::new_const("vant-hoff-i_s")` produce two distinct symbols
    of different sorts, the axiom predicate stays unbound, and the solver
    happily returns :sat against doctored ledgers (the sprint-5 bug).
    """
    cs = [_constraint(
        name="C001",
        assert_form=(
            "(~= (:osmotic-pressure-pa :s) "
            "(* (:vant-hoff-i :s) (:molarity :s) 8.314 (:temperature-k :s)) "
            ":tolerance 0.03)"
        ),
        tolerance=0.03,
    )]
    src = generate_axioms_source(cs)
    assert "pub fn predicate_is_real(name: &str) -> bool" in src
    # All four predicate-subject pairs were promoted to Real because R=8.314
    # appears in the same multiplication chain.
    for sym in ("osmotic-pressure-pa_s",
                "vant-hoff-i_s",
                "molarity_s",
                "temperature-k_s"):
        assert f'"{sym}" => true' in src, f"missing {sym!r} in predicate_is_real arms"


def test_predicate_is_real_helper_empty_for_int_only_constraints() -> None:
    """REQ-DSL-024: predicates that never appear in Real-promoted context
    return false. The helper still emits, but with no `true` arms — so a
    pure-Int constraint set (bermuda-style) keeps Int sort end-to-end.
    """
    cs = [_constraint(
        name="C001",
        assert_form="(= (:parishes-count :Bermuda) 9)",
    )]
    src = generate_axioms_source(cs)
    assert "pub fn predicate_is_real(name: &str) -> bool" in src
    assert "=> true" not in src or "parishes-count_Bermuda" not in src
    # int-only constraint should not promote anything to Real
    real_arms = [line for line in src.splitlines()
                 if "=> true," in line and "predicate_is_real" not in line]
    assert real_arms == [], f"unexpected Real arms: {real_arms}"


def test_generate_skips_non_z3_backends() -> None:
    """REQ-DSL-021: :egg constraints are still silently dropped from
    axioms.rs (Tier 4 work). REQ-DATALOG-041: :cozo constraints DO
    surface — but inside `cozo_constraints()`, not inside
    `assert_axioms`. The Z3 entry point must not see them.
    """
    cs = [_constraint(name="C001"),
          _constraint(name="C002", backend=":cozo",
                      assert_form="(some-cozo-thing)"),
          _constraint(name="C003", backend=":egg",
                      assert_form="(some-egg-thing)")]
    src = generate_axioms_source(cs)
    assert '"C001"' in src
    # Z3-entry-point (assert_axioms) must not see the :cozo / :egg ids;
    # split the source at `pub fn cozo_constraints` and inspect the Z3 half.
    assert_axioms_half, _, cozo_half = src.partition("pub fn cozo_constraints")
    assert '"C002"' not in assert_axioms_half, (
        ":cozo constraints must not leak into assert_axioms; "
        "they belong in cozo_constraints()"
    )
    assert '"C003"' not in assert_axioms_half
    assert '"C003"' not in cozo_half, (
        ":egg constraints must not be emitted anywhere in axioms.rs (Tier 4)"
    )
    # :cozo constraints DO appear in the cozo_constraints() registry.
    assert '"C002"' in cozo_half, (
        "REQ-DATALOG-041: :cozo constraints must surface in cozo_constraints()"
    )


def test_tracker_map_links_constraint_to_claim_binding() -> None:
    """REQ-DSL-023: tracker map entries include constraint-id, track, defect."""
    cs = [_constraint(name="C001", track=":claim/id")]
    tm = generate_tracker_map(cs)
    assert Keyword("C001") in tm
    entry = tm[Keyword("C001")]
    assert entry[Keyword("constraint-id")] == "C001"
    assert entry[Keyword("defect")]        == Keyword("D13")


def test_unknown_backend_raises() -> None:
    """REQ-DSL-021: unknown backend raises CodegenError."""
    cs = [_constraint(name="CX", backend=":mystery")]
    with pytest.raises(CodegenError, match="unknown backend"):
        generate_axioms_source(cs)


def test_missing_on_unsat_raises() -> None:
    """REQ-DSL-021: missing on-unsat raises CodegenError."""
    cs = [_constraint(name="CX")]
    cs[0].pop(Keyword("on-unsat"))
    with pytest.raises(CodegenError, match="missing on-unsat"):
        generate_axioms_source(cs)


def test_emitted_source_is_compilable_under_cargo_check(tmp_path: Path) -> None:
    """Soft check: generated axioms.rs string has balanced braces and smt feature gate.

    REQ-VERIFIER-BUILD-010: byte-deterministic output shape.
    REQ-VERIFIER-BUILD-011: cargo check gate is Task 2.5.
    """
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src = generate_axioms_source(cs)
    assert src.count("{") == src.count("}")
    assert src.count("(") == src.count(")")
    assert '#[cfg(feature = "smt")]' in src


def test_output_is_byte_deterministic() -> None:
    """REQ-VERIFIER-BUILD-010: two calls with same input produce identical output."""
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src1 = generate_axioms_source(cs)
    src2 = generate_axioms_source(cs)
    assert src1 == src2
