# skills/neurosym-forge/tests/test_codegen_kg.py
"""Tests for codegen_kg.py — kg.rs generation from queries.edn.

REQ-DSL-030: defquery expander emits intermediate edn.
REQ-DSL-031: kg.rs runs compiled queries via Cozo and returns row vectors.
"""
from __future__ import annotations

import pytest

from scripts.codegen_kg import (
    generate_kg_source,
    cozo_script_from_query,
    CodegenError,
)
from scripts._edn_reader import Keyword


def _query(name="Q001",
           find=None,
           where=None,
           on_result=None):
    return {
        Keyword("id"):        name,
        Keyword("backend"):   Keyword("cozo"),
        Keyword("find"):      find or [[Keyword("claim")]],
        Keyword("where"):     where or [
            [Keyword("claim/load-bearing"), [Keyword("claim")], True],
        ],
        Keyword("on-result"): on_result or {
            Keyword("defect"):   Keyword("posterior-floor"),
            Keyword("severity"): Keyword("warning"),
        },
    }


def test_cozo_script_simple_find_where() -> None:
    q = _query()
    script = cozo_script_from_query(q)
    assert "?[claim]" in script or "?[?claim]" in script
    assert "claim/load-bearing" in script


def test_cozo_script_handles_comparison_predicate() -> None:
    q = _query(where=[
        [Keyword("claim/posterior"), [Keyword("claim")], [Keyword("p")]],
        ["<", [Keyword("p")], 0.80],
    ])
    script = cozo_script_from_query(q)
    assert "<" in script
    assert "0.8" in script or "0.80" in script


def test_generate_kg_source_includes_dispatch_table() -> None:
    src = generate_kg_source([_query(name="Q001"), _query(name="Q002")])
    assert "// GENERATED BY neurosym-forge codegen_kg" in src
    assert "fn ingest_and_summarize" in src
    assert '"Q001"' in src
    assert '"Q002"' in src


def test_generate_kg_source_routes_results_to_defects() -> None:
    src = generate_kg_source([_query(name="Q001",
                                     on_result={Keyword("defect"): Keyword("D14"),
                                                Keyword("severity"): Keyword("warning")})])
    assert "D14" in src
    assert "warning" in src


def test_unknown_backend_raises() -> None:
    q = _query()
    q[Keyword("backend")] = Keyword("mystery")
    with pytest.raises(CodegenError, match="unknown backend"):
        generate_kg_source([q])


def test_generate_kg_source_balanced_braces() -> None:
    src = generate_kg_source([_query(name="Q001"), _query(name="Q002")])
    assert src.count("{") == src.count("}")
    assert src.count("(") == src.count(")")


def test_generate_kg_source_empty_queries() -> None:
    src = generate_kg_source([])
    assert "// GENERATED BY neurosym-forge codegen_kg" in src
    assert "fn ingest_and_summarize" in src
    assert "no queries declared" in src
