# skills/neurosym-forge/tests/test_codegen_axioms.py
"""Tests for codegen_axioms: generate axioms.rs + tracker map.

REQ-DSL-021: axioms.rs codegen with assert_and_track per constraint.
REQ-DSL-022: ~= (approximate-equality) operator desugaring.
REQ-DSL-023: axioms-tracker-map.edn bidirectional traceability.
REQ-VERIFIER-BUILD-010: byte-deterministic output.
"""
from __future__ import annotations

from pathlib import Path
import pytest

from scripts.codegen_axioms import (
    generate_axioms_source,
    generate_tracker_map,
    CodegenError,
)
from scripts._edn_reader import Keyword, Symbol


def _constraint(name="C001",
                backend=":z3",
                assert_form="(= (:parishes-count :Bermuda) 9)",
                tolerance=None,
                track=":claim/id",
                defect=":D13",
                severity=":critical",
                message="parish count off"):
    return {
        Keyword("id"):        name,
        Keyword("backend"):   Keyword(backend.lstrip(":")),
        Keyword("assert"):    assert_form,            # stored as EDN-printed string
        Keyword("tolerance"): tolerance,
        Keyword("track"):     Keyword(track.lstrip(":").replace("/", "_")) if track.startswith(":") else track,
        Keyword("on-unsat"):  {
            Keyword("defect"):   Keyword(defect.lstrip(":")),
            Keyword("severity"): Keyword(severity.lstrip(":")),
            Keyword("message"):  message,
        },
    }


def test_generate_simple_z3_int_constraint() -> None:
    """REQ-DSL-021: basic z3 constraint produces assert_and_track."""
    cs = [_constraint(name="C001", assert_form="(= (:parishes-count :Bermuda) 9)")]
    src = generate_axioms_source(cs)
    assert "// GENERATED BY neurosym-forge codegen_axioms" in src
    assert "pub fn assert_axioms" in src
    assert "assert_and_track" in src
    # Tracker name uses the constraint id when no claim binding exists.
    assert '"C001"' in src


def test_generate_approx_equality_emits_tolerance_clamp() -> None:
    """REQ-DSL-022: ~= desugars to |a - b| <= tolerance."""
    cs = [_constraint(name="C002",
                      assert_form="(~= (:osmotic-pressure-pa :sample) (* (:vant-hoff-i :sample) 8.314) :tolerance 0.03)",
                      tolerance=0.03)]
    src = generate_axioms_source(cs)
    # |a - b| <= ε desugaring lives in the emitted source as a Real difference + le.
    assert "0.03" in src
    assert "tolerance" in src.lower() or "approx" in src.lower()


def test_generate_multiple_constraints_each_tracked_uniquely() -> None:
    """REQ-DSL-021: each constraint gets its own tracker."""
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src = generate_axioms_source(cs)
    assert src.count("assert_and_track") >= 2
    assert '"C001"' in src
    assert '"C002"' in src


def test_predicate_is_real_helper_lists_promoted_predicates() -> None:
    """REQ-DSL-024: codegen emits `predicate_is_real(name)` enumerating
    every predicate-subject symbol that ended up Real-typed (because some
    sibling subexpression contained a float literal). smt.rs queries this
    to pick the matching Z3 sort for value-bindings; without it, axioms
    referencing `Real::new_const("vant-hoff-i_s")` and value-bindings
    using `Int::new_const("vant-hoff-i_s")` produce two distinct symbols
    of different sorts, the axiom predicate stays unbound, and the solver
    happily returns :sat against doctored ledgers (the sprint-5 bug).
    """
    cs = [_constraint(
        name="C001",
        assert_form=(
            "(~= (:osmotic-pressure-pa :s) "
            "(* (:vant-hoff-i :s) (:molarity :s) 8.314 (:temperature-k :s)) "
            ":tolerance 0.03)"
        ),
        tolerance=0.03,
    )]
    src = generate_axioms_source(cs)
    assert "pub fn predicate_is_real(name: &str) -> bool" in src
    # All four predicate-subject pairs were promoted to Real because R=8.314
    # appears in the same multiplication chain.
    for sym in ("osmotic-pressure-pa_s",
                "vant-hoff-i_s",
                "molarity_s",
                "temperature-k_s"):
        assert f'"{sym}" => true' in src, f"missing {sym!r} in predicate_is_real arms"


def test_predicate_is_real_helper_empty_for_int_only_constraints() -> None:
    """REQ-DSL-024: predicates that never appear in Real-promoted context
    return false. The helper still emits, but with no `true` arms — so a
    pure-Int constraint set (bermuda-style) keeps Int sort end-to-end.
    """
    cs = [_constraint(
        name="C001",
        assert_form="(= (:parishes-count :Bermuda) 9)",
    )]
    src = generate_axioms_source(cs)
    assert "pub fn predicate_is_real(name: &str) -> bool" in src
    assert "=> true" not in src or "parishes-count_Bermuda" not in src
    # int-only constraint should not promote anything to Real
    real_arms = [line for line in src.splitlines()
                 if "=> true," in line and "predicate_is_real" not in line]
    assert real_arms == [], f"unexpected Real arms: {real_arms}"


def test_generate_routes_backends_to_separate_emitters() -> None:
    """REQ-EQSAT-041 (Phase H): :egg constraints route through
    `_emit_egg_block` into the axioms.rs body — eqsat::prove_equiv at
    runtime.
    REQ-DATALOG-041 (Phase I): :cozo constraints surface inside
    `cozo_constraints()`, not inside `assert_axioms`. The Z3 entry point
    must not see them.
    """
    cs = [
        _constraint(name="C001"),  # :z3
        _constraint(name="C002", backend=":cozo",
                    assert_form="(some-cozo-thing)"),
        _constraint(name="C003", backend=":egg",
                    assert_form="(= (:foo :s) (:bar :s))"),
    ]
    src = generate_axioms_source(cs)
    assert_axioms_half, _, cozo_half = src.partition("pub fn cozo_constraints")
    # :z3 lands in the assert_axioms body
    assert '"C001"' in assert_axioms_half
    # :egg lands in the assert_axioms body too (via eqsat::prove_equiv shim)
    assert '"C003"' in assert_axioms_half, (
        ":egg constraints should route through _emit_egg_block into "
        "the assert_axioms body (Phase H, REQ-EQSAT-041)"
    )
    # :cozo lands in cozo_constraints() registry, NOT in assert_axioms
    assert '"C002"' not in assert_axioms_half, (
        ":cozo constraints must not leak into assert_axioms; "
        "they belong in cozo_constraints()"
    )
    assert '"C002"' in cozo_half, (
        "REQ-DATALOG-041: :cozo constraints must surface in cozo_constraints()"
    )


def test_tracker_map_links_constraint_to_claim_binding() -> None:
    """REQ-DSL-023: tracker map entries include constraint-id, track, defect."""
    cs = [_constraint(name="C001", track=":claim/id")]
    tm = generate_tracker_map(cs)
    assert Keyword("C001") in tm
    entry = tm[Keyword("C001")]
    assert entry[Keyword("constraint-id")] == "C001"
    assert entry[Keyword("defect")]        == Keyword("D13")


def test_unknown_backend_raises() -> None:
    """REQ-DSL-021: unknown backend raises CodegenError."""
    cs = [_constraint(name="CX", backend=":mystery")]
    with pytest.raises(CodegenError, match="unknown backend"):
        generate_axioms_source(cs)


def test_missing_on_unsat_raises() -> None:
    """REQ-DSL-021: missing on-unsat raises CodegenError."""
    cs = [_constraint(name="CX")]
    cs[0].pop(Keyword("on-unsat"))
    with pytest.raises(CodegenError, match="missing on-unsat"):
        generate_axioms_source(cs)


def test_emitted_source_is_compilable_under_cargo_check(tmp_path: Path) -> None:
    """Soft check: generated axioms.rs string has balanced braces and smt feature gate.

    REQ-VERIFIER-BUILD-010: byte-deterministic output shape.
    REQ-VERIFIER-BUILD-011: cargo check gate is Task 2.5.
    """
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src = generate_axioms_source(cs)
    assert src.count("{") == src.count("}")
    assert src.count("(") == src.count(")")
    assert '#[cfg(feature = "smt")]' in src


def test_output_is_byte_deterministic() -> None:
    """REQ-VERIFIER-BUILD-010: two calls with same input produce identical output."""
    cs = [_constraint(name="C001"),
          _constraint(name="C002", assert_form="(= (:population :Bermuda) 64000)")]
    src1 = generate_axioms_source(cs)
    src2 = generate_axioms_source(cs)
    assert src1 == src2


# ---------------------------------------------------------------- REQ-PERF-040..043


def test_emits_axioms_for_subject_accessor() -> None:
    """REQ-PERF-040: codegen emits a `axioms_for_subject(solver, subject)`
    accessor so `smt::check_all` can build a per-subject partition.
    """
    cs = [
        _constraint(name="C001",
                    assert_form="(= (:parishes-count :Bermuda) 9)"),
        _constraint(name="C002",
                    assert_form="(= (:population :Atlantis) 1)"),
    ]
    src = generate_axioms_source(cs)
    assert "pub fn axioms_for_subject(solver: &Solver, subject: &str)" in src
    # Each subject gets its own match arm.
    assert '"Bermuda" =>' in src
    assert '"Atlantis" =>' in src
    # The default arm exists so unknown subjects compile cleanly.
    assert "_ =>" in src


def test_emits_axioms_shared_for_cross_subject_constraints() -> None:
    """REQ-PERF-043: a constraint that references two distinct subjects
    is routed into `axioms_shared`, not into either subject's bucket.
    """
    cs = [
        _constraint(name="C001",
                    assert_form="(= (:parishes-count :Bermuda) 9)"),
        # Cross-subject: references both :Bermuda and :Cayman.
        _constraint(name="C002",
                    assert_form="(= (:parishes-count :Bermuda) (:parishes-count :Cayman))"),
    ]
    src = generate_axioms_source(cs)
    assert "pub fn axioms_shared(solver: &Solver)" in src
    # The cross-subject constraint must not show up in any per-subject arm.
    # We check that the tracker for C002 appears strictly within
    # axioms_shared by slicing on the function header.
    shared_start = src.index("pub fn axioms_shared(solver: &Solver)")
    shared_end   = src.index("\npub fn", shared_start + 1)
    shared_body  = src[shared_start:shared_end]
    assert '"C002"' in shared_body
    # And C001 must NOT be in shared (it has exactly one subject).
    assert '"C001"' not in shared_body


def test_emits_axioms_subjects_enumerator() -> None:
    """REQ-PERF-040: codegen emits `axioms_subjects()` so `smt::check_all`
    can iterate every declared subject deterministically.
    """
    cs = [
        _constraint(name="C001",
                    assert_form="(= (:parishes-count :Bermuda) 9)"),
        _constraint(name="C002",
                    assert_form="(= (:population :Atlantis) 1)"),
    ]
    src = generate_axioms_source(cs)
    assert "pub fn axioms_subjects() -> &'static [&'static str]" in src
    # Sorted (Atlantis < Bermuda) for deterministic dispatch order.
    idx_a = src.index('"Atlantis"')
    idx_b = src.index('"Bermuda"')
    assert idx_a < idx_b


def test_assert_axioms_aggregator_calls_partitioned_accessors() -> None:
    """REQ-PERF-040: the legacy `assert_axioms(solver)` entry point stays
    around for callers that haven't migrated, and now calls
    `axioms_for_subject` per subject plus `axioms_shared`.
    """
    cs = [
        _constraint(name="C001",
                    assert_form="(= (:parishes-count :Bermuda) 9)"),
    ]
    src = generate_axioms_source(cs)
    assert "pub fn assert_axioms(solver: &Solver)" in src
    agg_start = src.index("pub fn assert_axioms(solver: &Solver)")
    agg_end   = src.index("\n}\n", agg_start) + 3
    agg_body  = src[agg_start:agg_end]
    assert 'axioms_for_subject(solver, "Bermuda")' in agg_body
    assert "axioms_shared(solver)" in agg_body


# -------- REQ-CORPUS-050..056: corpus-scope constraints --------


def test_corpus_scope_constraint_emits_axioms_corpus() -> None:
    """REQ-CORPUS-050, 051: a `:scope :corpus` constraint emits a
    `pub fn axioms_corpus(solver)` accessor and lands the tracker block
    in its body, not in `axioms_for_subject` or `axioms_shared`.
    """
    c = _constraint(
        name="C-corp",
        assert_form="(>= (:trial-n :t) 10)",
    )
    c[Keyword("scope")] = Keyword("corpus")
    src = generate_axioms_source([c])
    assert "pub fn axioms_corpus(solver: &Solver)" in src
    # The tracker for C-corp lives strictly within axioms_corpus.
    corpus_start = src.index("pub fn axioms_corpus(solver: &Solver)")
    corpus_end   = src.index("\npub fn", corpus_start + 1)
    corpus_body  = src[corpus_start:corpus_end]
    assert '"C-corp"' in corpus_body
    # And NOT in axioms_for_subject or axioms_shared.
    fs_start = src.index("pub fn axioms_for_subject(solver: &Solver, subject: &str)")
    fs_end   = src.index("\npub fn", fs_start + 1)
    assert '"C-corp"' not in src[fs_start:fs_end]
    shared_start = src.index("pub fn axioms_shared(solver: &Solver)")
    shared_end   = src.index("\npub fn", shared_start + 1)
    assert '"C-corp"' not in src[shared_start:shared_end]


def test_subject_scope_default_unaffected_by_corpus_addition() -> None:
    """REQ-CORPUS-050: omitting `:scope` preserves Phase J behaviour.
    A single-subject constraint still lands in the per-subject bucket,
    not in axioms_corpus.
    """
    cs = [
        _constraint(name="C001",
                    assert_form="(= (:parishes-count :Bermuda) 9)"),
    ]
    src = generate_axioms_source(cs)
    # axioms_corpus exists but is empty (no `assert_and_track` inside).
    corpus_start = src.index("pub fn axioms_corpus(solver: &Solver)")
    corpus_end   = src.index("\npub fn", corpus_start + 1)
    corpus_body  = src[corpus_start:corpus_end]
    assert "assert_and_track" not in corpus_body
    # The C001 tracker lives in the per-subject bucket.
    fs_start = src.index("pub fn axioms_for_subject(solver: &Solver, subject: &str)")
    fs_end   = src.index("\npub fn", fs_start + 1)
    assert '"C001"' in src[fs_start:fs_end]


def test_axioms_corpus_ids_enumerates_corpus_scope_constraints() -> None:
    """REQ-CORPUS-053: codegen emits `axioms_corpus_ids()` so smt.rs can
    map unsat-core trackers back to corpus-scope constraint ids when
    building the verdict's `:corpus-defects` field.
    """
    c1 = _constraint(name="C-sub", assert_form="(= (:p :x) 1)")
    c2 = _constraint(name="C-corp1", assert_form="(>= (:trial-n :t) 10)")
    c2[Keyword("scope")] = Keyword("corpus")
    c3 = _constraint(name="C-corp2", assert_form="(<= (:trial-n :u) 100)")
    c3[Keyword("scope")] = Keyword("corpus")
    src = generate_axioms_source([c1, c2, c3])
    assert "pub fn axioms_corpus_ids() -> &'static [&'static str]" in src
    ids_start = src.index("pub fn axioms_corpus_ids()")
    ids_end   = src.index("\n}\n", ids_start)
    ids_body  = src[ids_start:ids_end]
    assert '"C-corp1"' in ids_body
    assert '"C-corp2"' in ids_body
    assert '"C-sub"' not in ids_body


def test_bad_scope_value_raises() -> None:
    """REQ-CORPUS-050: any :scope value other than :subject/:corpus
    is rejected at codegen time."""
    c = _constraint(name="C-bad", assert_form="(= (:p :s) 1)")
    c[Keyword("scope")] = Keyword("bogus")
    with pytest.raises(CodegenError):
        generate_axioms_source([c])


def test_corpus_scope_aggregator_calls_axioms_corpus() -> None:
    """REQ-CORPUS-051: when any corpus constraint is declared, the legacy
    `assert_axioms` aggregator wires `axioms_corpus(solver)` after
    `axioms_shared(solver)`.
    """
    c = _constraint(name="C-corp", assert_form="(>= (:trial-n :t) 10)")
    c[Keyword("scope")] = Keyword("corpus")
    src = generate_axioms_source([c])
    agg_start = src.index("pub fn assert_axioms(solver: &Solver)")
    agg_end   = src.index("\n}\n", agg_start) + 3
    agg_body  = src[agg_start:agg_end]
    assert "axioms_corpus(solver)" in agg_body


# -------- REQ-DSL-050..055: multi-valued predicates --------

def test_vector_predicate_emits_z3_array() -> None:
    """REQ-DSL-051: [:vector :real] return → Z3 Array<Int, Real> symbol."""
    cs = [_constraint(
        name="C-vec",
        assert_form="(= (select (:solutes :s) 0) 0)",
    )]
    schema = {
        Keyword("solutes"): {
            Keyword("arg-sorts"): [Keyword("solution")],
            Keyword("return"):    [Keyword("vector"), Keyword("real")],
        },
    }
    src = generate_axioms_source(cs, schema=schema)
    assert "Array" in src, "vector predicate must lower to a Z3 Array<...>"
    assert "Real" in src
    # The helper predicate_is_vector lists vector-typed predicate symbols.
    assert "pub fn predicate_is_vector(name: &str) -> bool" in src
    assert '"solutes_s" => true' in src


def test_set_predicate_emits_z3_set() -> None:
    """REQ-DSL-052: [:set :chapter] return → Z3 Set<...> symbol."""
    cs = [_constraint(
        name="C-set",
        assert_form="(= (count (:upstream-chapters :c)) 0)",
    )]
    schema = {
        Keyword("upstream-chapters"): {
            Keyword("arg-sorts"): [Keyword("chapter")],
            Keyword("return"):    [Keyword("set"), Keyword("chapter")],
        },
    }
    src = generate_axioms_source(cs, schema=schema)
    assert "Set" in src, "set predicate must lower to a Z3 Set<...>"
    assert "pub fn predicate_is_vector(name: &str) -> bool" in src
    # set-typed predicates are NOT vectors; predicate_is_vector returns false.
    assert '"upstream-chapters_c" => true' not in src


def test_count_aggregate_uses_paired_length_symbol() -> None:
    """REQ-DSL-053: (count vec) lowers to the paired <var>_len Int symbol."""
    cs = [_constraint(
        name="C-count",
        assert_form="(= (count (:solutes :s)) 3)",
    )]
    schema = {
        Keyword("solutes"): {
            Keyword("arg-sorts"): [Keyword("solution")],
            Keyword("return"):    [Keyword("vector"), Keyword("real")],
        },
    }
    src = generate_axioms_source(cs, schema=schema)
    assert "solutes_s_len" in src, (
        "count(vec) must use the codegen's paired <var>_len Int symbol"
    )


def test_sum_aggregate_emits_array_fold() -> None:
    """REQ-DSL-053: (sum vec) over a known-length vector unrolls statically."""
    cs = [_constraint(
        name="C-sum",
        assert_form="(= (sum (:solutes :s)) 0)",
    )]
    schema = {
        Keyword("solutes"): {
            Keyword("arg-sorts"): [Keyword("solution")],
            Keyword("return"):    [Keyword("vector"), Keyword("real")],
        },
    }
    src = generate_axioms_source(cs, schema=schema)
    # Sum lowers to a fold over Array<Int, Real>::select(i).
    assert "select" in src
    # Either a chained .add or a Real::add fold; both encode the unrolled sum.
    assert ".add(" in src or "Real::add" in src


def test_forall_aggregate_emits_bounded_unroll() -> None:
    """REQ-DSL-053: (forall ?x in vec body) emits an array-indexed quantifier
    or bounded Bool::and unroll."""
    cs = [_constraint(
        name="C-forall",
        assert_form="(forall ?x in (:solutes :s) (= ?x 0))",
    )]
    schema = {
        Keyword("solutes"): {
            Keyword("arg-sorts"): [Keyword("solution")],
            Keyword("return"):    [Keyword("vector"), Keyword("real")],
        },
    }
    src = generate_axioms_source(cs, schema=schema)
    # The forall lowers to either a Z3 forall_const or a Bool::and over slices.
    assert "forall" in src.lower() or "Bool::and" in src


def test_schema_optional_back_compat() -> None:
    """Calling generate_axioms_source without schema= must still work
    (backwards-compatible default for projects predating REQ-DSL-050)."""
    cs = [_constraint(name="C001")]
    src = generate_axioms_source(cs)  # no schema kwarg
    assert "assert_and_track" in src
    # predicate_is_vector is emitted regardless, with no true arms when no
    # vector predicates exist.
    assert "pub fn predicate_is_vector(name: &str) -> bool" in src


# ---------------------------------------------------------------- encoder extensions

def test_generate_less_than_constraint_emits_lt_call() -> None:
    """REQ-SMT-040: `<` compiles to a Z3 `.lt(&rhs)` method call."""
    cs = [_constraint(
        name="C010",
        assert_form="(< (:parishes-count :Bermuda) 10)",
    )]
    src = generate_axioms_source(cs)
    assert ".lt(&" in src
    assert '"C010"' in src
    # No accidental fallback to `.eq` for a strict-inequality form.
    assert "lhs.eq(&rhs)" not in src or src.count(".lt(&") >= 1


def test_generate_less_equal_constraint_emits_le_call() -> None:
    """REQ-SMT-040: `<=` compiles to a Z3 `.le(&rhs)` method call."""
    cs = [_constraint(
        name="C011",
        assert_form="(<= (:parishes-count :Bermuda) 9)",
    )]
    src = generate_axioms_source(cs)
    assert ".le(&" in src
    assert '"C011"' in src


def test_generate_greater_than_constraint_emits_gt_call() -> None:
    """REQ-SMT-041: `>` compiles to a Z3 `.gt(&rhs)` method call."""
    cs = [_constraint(
        name="C012",
        assert_form="(> (:population :Bermuda) 60000)",
    )]
    src = generate_axioms_source(cs)
    assert ".gt(&" in src
    assert '"C012"' in src


def test_generate_greater_equal_constraint_emits_ge_call() -> None:
    """REQ-SMT-041: `>=` compiles to a Z3 `.ge(&rhs)` method call."""
    cs = [_constraint(
        name="C013",
        assert_form="(>= (:population :Bermuda) 60000)",
    )]
    src = generate_axioms_source(cs)
    assert ".ge(&" in src
    assert '"C013"' in src


def test_generate_division_subexpression_emits_div_call() -> None:
    """REQ-SMT-042: `/` compiles to a Z3 `.div(&rhs)` method call when
    used inside a numeric subexpression (here an equality RHS)."""
    cs = [_constraint(
        name="C014",
        assert_form="(= (:density :Sample) (/ (:mass :Sample) (:volume :Sample)))",
    )]
    src = generate_axioms_source(cs)
    assert ".div(&" in src
    assert '"C014"' in src


def test_generate_ite_constraint_emits_ite_call() -> None:
    """REQ-SMT-043: `ite` compiles to a Z3 `cond.ite(&then, &else)` call."""
    cs = [_constraint(
        name="C015",
        assert_form=(
            "(ite (< (:parishes-count :Bermuda) 10) "
            "(< (:population :Bermuda) 70000) "
            "(> (:population :Bermuda) 70000))"
        ),
    )]
    src = generate_axioms_source(cs)
    assert ".ite(&" in src
    assert '"C015"' in src


def test_unsupported_operator_errors() -> None:
    """REQ-SMT-044: an unknown assert head produces a CodegenError that
    names the full supported set so authors can self-correct without
    grepping for the operator table."""
    cs = [_constraint(
        name="C016",
        assert_form="(xor (:a :S) (:b :S))",
    )]
    with pytest.raises(CodegenError) as excinfo:
        generate_axioms_source(cs)
    msg = str(excinfo.value)
    assert "'xor'" in msg
    # The error must enumerate the supported set; spot-check a representative.
    for op in ("=", "<", "<=", ">", ">=", "/", "ite"):
        assert repr(op) in msg, f"missing {op!r} in supported-set error: {msg}"


# ---------------------------------------------------------------- v0.5 boolean connectives

def test_generate_and_assertion():
    # (and (< (:f-stake :e) 0.3) (>= (:domain-count :e) 3))
    constraints = [
        {Keyword("id"):       "CB001",
         Keyword("backend"):  Keyword("z3"),
         Keyword("assert"):   (Symbol("and"),
                               (Symbol("<"), (Keyword("f-stake"), Keyword("e")), 0.3),
                               (Symbol(">="), (Keyword("domain-count"), Keyword("e")), 3)),
         Keyword("on-unsat"): {Keyword("defect"):   Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"):  "threshold fails"}}
    ]
    out = generate_axioms_source(constraints)
    assert "Bool::and" in out
    assert "Real::lt" in out or ".lt(&" in out
    assert "Real::ge" in out or "Int::ge" in out or ".ge(&" in out


def test_generate_or_assertion():
    constraints = [
        {Keyword("id"):       "CB002",
         Keyword("backend"):  Keyword("z3"),
         Keyword("assert"):   (Symbol("or"),
                               (Symbol("="), (Keyword("status"), Keyword("e")), "ok"),
                               (Symbol("="), (Keyword("status"), Keyword("e")), "pending")),
         Keyword("on-unsat"): {Keyword("defect"):   Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"):  "status mismatch"}}
    ]
    out = generate_axioms_source(constraints)
    assert "Bool::or" in out


def test_generate_nested_and_or():
    inner_or = (Symbol("or"),
                (Symbol("="), (Keyword("color"), Keyword("e")), "red"),
                (Symbol("="), (Keyword("color"), Keyword("e")), "blue"))
    body = (Symbol("and"),
            (Symbol(">="), (Keyword("count"), Keyword("e")), 1),
            inner_or)
    constraints = [
        {Keyword("id"):       "CB003",
         Keyword("backend"):  Keyword("z3"),
         Keyword("assert"):   body,
         Keyword("on-unsat"): {Keyword("defect"):   Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"):  "nested check"}}
    ]
    out = generate_axioms_source(constraints)
    assert "Bool::and" in out
    assert "Bool::or" in out


def test_generate_not_assertion():
    constraints = [
        {Keyword("id"): "CB101",
         Keyword("backend"): Keyword("z3"),
         Keyword("assert"): (Symbol("not"),
                             (Symbol("="), (Keyword("status"), Keyword("e")), "failed")),
         Keyword("track"): Keyword("CB101"),
         Keyword("on-unsat"): {Keyword("defect"): Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"): "status check"}}
    ]
    out = generate_axioms_source(constraints)
    assert ".not()" in out


def test_generate_implies_assertion():
    constraints = [
        {Keyword("id"): "CB102",
         Keyword("backend"): Keyword("z3"),
         Keyword("assert"): (Symbol("=>"),
                             (Symbol("<"), (Keyword("f-stake"), Keyword("e")), 0.3),
                             (Symbol("<="), (Keyword("max-per-domain-fraction"), Keyword("e")), 0.25)),
         Keyword("track"): Keyword("CB102"),
         Keyword("on-unsat"): {Keyword("defect"): Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"): "implication check"}}
    ]
    out = generate_axioms_source(constraints)
    assert ".implies(" in out


# ---------------------------------------------------------------- bound variable resolution (REQ-SMT-053)

def test_unbound_variable_reference_raises():
    # Plain `(= ?x 5)` outside any quantifier scope must raise.
    constraints = [
        {Keyword("id"): "CB201",
         Keyword("backend"): Keyword("z3"),
         Keyword("assert"): (Symbol("="), Symbol("?x"), 5),
         Keyword("track"): Keyword("CB201"),
         Keyword("on-unsat"): {Keyword("defect"): Keyword("D13"),
                               Keyword("severity"): Keyword("critical"),
                               Keyword("message"): "unbound var should fail"}}
    ]
    with pytest.raises(CodegenError, match=r"unbound variable '\?x'"):
        generate_axioms_source(constraints)


def test_bound_variable_reference_resolves_to_z3_const():
    from scripts.codegen_axioms import _emit_expr
    bound = {"?x": "x_const"}
    rendered = _emit_expr(Symbol("?x"), bound_vars=bound)
    assert rendered == "x_const"


# ---------------------------------------------------------------- v0.5 golden fixture (REQ-BOOKLOGIC-051..053, REQ-SMT-055)

def test_extended_operators_v0_5_golden_fixture():
    """Pin canonical AST shapes for v0.5 extended operators (and/or/not/=>/forall/exists)."""
    from scripts._edn_reader import read_edn
    fixture_path = Path(__file__).parent / "golden" / "extended_operators_v0_5.edn"
    raw = fixture_path.read_text(encoding="utf-8")
    fixture = read_edn(raw)
    for case in fixture[Keyword("cases")]:
        constraint = {
            Keyword("id"): case[Keyword("name")],
            Keyword("backend"): Keyword("z3"),
            Keyword("assert"): case[Keyword("assert")],
            Keyword("track"): Keyword("claim/id"),
            Keyword("on-unsat"): {
                Keyword("defect"): Keyword("D13"),
                Keyword("severity"): Keyword("critical"),
                Keyword("message"): "golden fixture check",
            },
        }
        sorts = list(case.get(Keyword("sorts"), []))
        out = generate_axioms_source([constraint], sorts=sorts)
        expected = case[Keyword("expected-z3-call")]
        assert expected in out, (
            f"case {case[Keyword('name')]!r}: expected {expected!r} in emitted source"
        )


def test_approx_with_inline_tolerance_in_assert_form() -> None:
    """approx= constraints whose CLJS intermediate carried :tolerance nil
    must still extract the tolerance from inside the assert form itself
    when it is specified as a trailing :tolerance key-value pair."""
    c = _constraint(
        name="C-INLINE-TOL",
        assert_form="(approx= (:p-empty :s) (- 1.0 (:phi :s)) :tolerance 0.01)",
        tolerance=None,
    )
    src = generate_axioms_source([c])
    assert "C-INLINE-TOL" in src
    # _emit_approx_block raises CodegenError if tolerance is None at emit
    # time, so reaching this assertion means inline extraction worked.
    assert "assert_and_track" in src


def test_approx_always_uses_real_typing() -> None:
    """_emit_approx_block multiplies by Real::from_rational eps, so both
    sides of approx= must be Real-typed regardless of whether any subtree
    contained a float literal. Int-typed sides would produce Int * Real."""
    # Both sides scalar-int subtrees; without the always-Real fix this would
    # emit Int::new_const and fail to compile in Rust.
    c = _constraint(
        name="C-APPROX-REAL",
        assert_form="(approx= (:a :s) (:b :s) :tolerance 0.001)",
        tolerance=None,
    )
    src = generate_axioms_source([c])
    # The emitted block declares the predicate variables as Real (not Int).
    assert 'Real::new_const("a_s")' in src
    assert 'Real::new_const("b_s")' in src
    assert 'Int::new_const("a_s")' not in src


def test_mod_operator_emits_rem_call() -> None:
    """(mod dividend divisor) compiles to Int::rem; predicate args are
    typed Int. Required by EpochPoET's epoch-length-vs-Casper-sub-epoch
    constraint."""
    c = _constraint(
        name="C-MOD",
        assert_form="(= (mod (:epoch-length :s) 32) 0)",
        tolerance=None,
    )
    src = generate_axioms_source([c])
    assert "C-MOD" in src
    # The mod operator emits Int::rem(&...).
    assert ".rem(&" in src
